### ISSUE TITLE
@AllArgsConstructor - Fields not being initialized (even though they are)

### ISSUE THREAD

**Issue by trietsch** [mplushnikov/lombok-intellij-plugin#420] opened 2017-09-18 13:37 UTC
### Short description
For a class with private final fields, when using the `@AllArgsConstructor`, IntelliJ keeps complaining about "fields not being initialized".

### Expected behavior
IntelliJ not complaining about fields not being initialized.

### Version information

 * **IDEA Version:** IntelliJ IDEA 2017.1.5, Build #IU-171.4694.70, built on July 4, 2017
 * **JDK Version:** 1.8.0_112-release-736-b21 x86_64
 * **OS Type & Version:** Mac OS X 10.12.6
 * **Lombok Plugin Version:** 15.17.2
 * **Lombok Dependency Version:** lombok-plugin-0.15.17.2.jar

### Steps to reproduce
Since this does not happen always (for some classes I had the problem, but not for all), I'll include everything that might be relevant. These are the steps:
1. Create a class that implements a simple interface (the interface had a single method and was a simple POJO)
2. Annotate this class with `@Getter`, `@EqualsAndHashCode`, and `@AllArgsConstructor`

For some classes, IntelliJ will complain about fields note being initialized.

### Sample project
I've created a sample project, however, this project does not suffer from the bug.

### Additional information
To work around the bug, follow the following steps:
1. Add the `@RequiredArgsConstructor` (next to the `@AllArgsConstructor`)
2. Remove the `@AllArgsConstructor`
3. Add the `@AllArgsConstructor` back
4. Remove the `@RequiredArgsConstructor`

Now IntelliJ should not complain anymore.

**Comment by MrFant** [comment] 2018-08-07 13:24
That‘s work to me ,thanks

**Comment by mplushnikov** [comment] 2018-11-04 16:01
I can't reproduce this issue, if you find any example showing this behaviour, it would be extremely helpful!
I' ll close this for now, feel free to reopen the issue, if it still occurs!

**Closed by mplushnikov** 2018-11-04 16:01 UTC
