### ISSUE TITLE
Write-unsafe context exception on project without lombok.

### ISSUE THREAD

**Issue by dant3** [mplushnikov/lombok-intellij-plugin#460] opened 2018-03-15 15:42 UTC
### Short description
IDE fatal error occurs every time you open "Refactor" menu on a project without lombok usage.

### Expected behavior
No exception occurs

### Version information
IntelliJ IDEA 2017.2.5
Build #IC-172.4343.14, built on September 26, 2017
JRE: 1.8.0_152-release-915-b12 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.3

 * **Lombok Plugin Version:** 0.11.16
 * **Lombok Dependency Version:** None

### Stacktrace
If you are experiencing an issue and IntelliJ throws an error please provide the stacktrace.

```

Write-unsafe context! Model changes are allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details.
  current modality=ModalityState.NON_MODAL
  known modalities={ModalityState.NON_MODAL=true}
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.openapi.application.TransactionGuardImpl.assertWriteActionAllowed(TransactionGuardImpl.java:230)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitAllDocuments(PsiDocumentManagerBase.java:232)
	at de.plushnikov.intellij.plugin.action.delombok.BaseDelombokAction.isValidForFile(BaseDelombokAction.java:205)
	at de.plushnikov.intellij.plugin.action.delombok.BaseDelombokAction.update(BaseDelombokAction.java:135)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:132)
	at com.intellij.openapi.actionSystem.impl.Utils.doUpdate(Utils.java:235)
	at com.intellij.openapi.actionSystem.impl.Utils.updateGroupChild(Utils.java:312)
	at com.intellij.openapi.actionSystem.impl.Utils.hasChildrenWithState(Utils.java:286)
	at com.intellij.openapi.actionSystem.impl.Utils.hasVisibleChildren(Utils.java:252)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:194)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:100)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:341)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.fillMenu(ActionMenu.java:326)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.access$600(ActionMenu.java:54)
	at com.intellij.openapi.actionSystem.impl.ActionMenu$MenuListenerImpl.menuSelected(ActionMenu.java:280)
	at javax.swing.JMenu.fireMenuSelected(JMenu.java:1038)
	at javax.swing.JMenu$MenuChangeListener.stateChanged(JMenu.java:1118)
	at javax.swing.DefaultButtonModel.fireStateChanged(DefaultButtonModel.java:349)
	at javax.swing.DefaultButtonModel.setSelected(DefaultButtonModel.java:232)
	at javax.swing.JMenu.setSelected(JMenu.java:305)
	at com.apple.laf.ScreenMenu$2.run(ScreenMenu.java:135)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by mplushnikov** [comment] 2018-03-28 18:37
> Lombok Plugin Version: 0.11.16
This version is quite old, please update!
Duplicate of #308

**Closed by mplushnikov** 2018-03-28 18:37 UTC
