### ISSUE TITLE
could you make this plugin support the @UtilityClass

### ISSUE THREAD

**Issue by leduold** [mplushnikov/lombok-intellij-plugin#181] opened 2016-01-31 16:12 UTC
i can not find the static method which i have declared in my util class,when i use @UtilityClass in my project ..      
 
plugin version :0.9.6.14
could you make this plugin support the @UtilityClass ?

**Comment by leduold** [comment] 2016-01-31 16:18
lombok.experimental

**Comment by mplushnikov** [comment] 2016-01-31 17:48
This is duplicate of Support UtilityClass #143
It is not possible at the moment, I'm still investigating how to make it possible.

**Closed by mplushnikov** 2016-01-31 17:48 UTC
Labels: duplicate
