### ISSUE TITLE
plugin compatibility issue in IntelliJ IDEA 2018.2 EAP

### ISSUE THREAD

**Issue by krzyk** [mplushnikov/lombok-intellij-plugin#481] opened 2018-05-16 07:27 UTC
### Short description
plugin compatibility issue in IntelliJ IDEA 2018.2 EAP (a red text with "Plugin incompatible with the new build found: Lombok plugin")

### Expected behavior
No plugin incompatibility with new EAP

### Version information

 * **IDEA Version:** 182.2371.4
 * **JDK Version:** bundled from IDEA
 * **OS Type & Version:** Linux
 * **Lombok Plugin Version:** 0.17-2018.1
 * **Lombok Dependency Version:** edge

### Steps to reproduce
Check for updates in 2018.1, and the new window with upgrade shows the lombok plugin as incompatible.

**Comment by Fornori** [comment] 2018-05-16 11:49
Yep, I use JetBrains 2018.2 And all code, that must generated by lomok mark as red - not found (getter method, for example)

**Comment by Fornori** [comment] 2018-05-16 13:15
The issue is fixed in the version: 0.15.17.2

**Comment by AndroidIosWebEmbeddedFirmwareDver** [comment] 2018-05-22 08:39
![image](https://user-images.githubusercontent.com/8732312/40351297-a36e6468-5dde-11e8-9abb-df61e538554f.png)

**Comment by lvtanxi** [comment] 2018-05-28 02:01
me too

**Comment by mmoayyed** [comment] 2018-06-20 17:43
Is there something I can do to help resolve this issue? I have cloned and built the repo, but not sure where to go from here next. What needs changing, and how can the test be deployed or tested locally? Are there guidelines on how one could get started with changes for this project?

**Comment by kossmoboleat** [comment] 2018-06-21 20:11
There's only one that needs to be changed in the file gradle.properties. You probably only have to set `ideaVersion=2018.2`

**Comment by mplushnikov** [comment] 2018-06-23 21:15
Just uploaded a compatible plugin version for IntelliJ 2018.2 EAP

**Closed by mplushnikov** 2018-06-23 21:15 UTC

**Comment by cy4n** [comment] 2018-06-24 08:47
@mplushnikov you are awesome!

**Comment by hosswald** [comment] 2018-06-25 09:04
@mplushnikov 0.18-LATEST-EAP-SNAPSHOT is now compatible only with 182.3341+, which is the very newest version, so if I'm just one version behind I will not have a working plugin (I don't know if IntelliJ would deactivate the plugin, but at least it didn't update untill I told the Jetbrains Toolbox to update the EAP.

**Comment by maslbl4** [comment] 2018-07-26 11:13
@mplushnikov plugin 0.19-2018.1 not compatible with release IDEA 2018.2 :(
