### ISSUE TITLE
Crash on Idea 2016.3.4

### ISSUE THREAD

**Issue by paradoxfm** [mplushnikov/lombok-intellij-plugin#357] opened 2017-02-21 06:18 UTC
PSI and index do not match
Please report the problem to JetBrains with the file attached
 file=PsiJavaFile:SessionFactoryFacadeImpl.java, file.class=class com.intellij.psi.impl.source.PsiJavaFileImpl, file.lang=Language: JAVA, modStamp=0
 tree consistent
 stub debugInfo=created in getStubTree(), no AST; with backReference
 document before=null
latestIndexedStub=null
 viewProvider=SingleRootFileViewProvider{myVirtualFile=jar://C:/Users/IGurkin/.m2/repository/ru/poidem/orm/oas-orm-core/1.4.168/oas-orm-core-1.4.168-sources.jar!/ru/poidem/orm/dao/impl/SessionFactoryFacadeImpl.java, content=VirtualFileContent{size=2785}}
 viewProvider stamp: 0; file stamp: 0; file modCount: 1486016783994; file length: 2785
 doc saved: true; doc stamp: 0; doc size: 2591; committed: true
in many projects: false
indexing info: no data
java.lang.Throwable
	at com.intellij.util.ExceptionUtil.currentStackTrace(ExceptionUtil.java:65)
	at com.intellij.psi.impl.DebugUtil.currentStackTrace(DebugUtil.java:501)
	at com.intellij.psi.stubs.StubProcessingHelper.stubTreeAndIndexDoNotMatch(StubProcessingHelper.java:38)
	at com.intellij.psi.stubs.StubProcessingHelperBase.a(StubProcessingHelperBase.java:176)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:166)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:52)
	at com.intellij.psi.stubs.StubIndexImpl$2.process(StubIndexImpl.java:333)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:684)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:672)
	at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:81)
	at com.intellij.psi.stubs.StubIndexImpl.a(StubIndexImpl.java:359)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:325)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:146)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:135)
	at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.get(JavaFullClassNameIndex.java:48)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.doFindClasses(JavaFileManagerImpl.java:96)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClasses(JavaFileManagerImpl.java:83)
	at com.intellij.psi.impl.PsiElementFinderImpl.findClasses(PsiElementFinderImpl.java:60)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClasses(JavaPsiFacadeImpl.java:164)
	at com.intellij.psi.impl.file.PsiPackageImpl.getCachedClassesByName(PsiPackageImpl.java:212)
	at com.intellij.psi.impl.file.PsiPackageImpl.findClassByShortName(PsiPackageImpl.java:278)
	at com.intellij.psi.impl.file.PsiPackageImpl.processDeclarations(PsiPackageImpl.java:317)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processDeclarationsNoGuess(PsiJavaFileBaseImpl.java:352)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processDeclarations(PsiJavaFileBaseImpl.java:309)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:69)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:51)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:218)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:149)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:458)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:55)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:360)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:352)
	at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:191)
	at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:188)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:188)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:754)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:743)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:387)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:380)
	at com.intellij.psi.impl.source.PsiClassReferenceType.resolveGenerics(PsiClassReferenceType.java:145)
	at com.intellij.psi.impl.TypeCorrector.correctType(TypeCorrector.java:55)
	at com.intellij.psi.impl.PsiClassImplUtil.correctType(PsiClassImplUtil.java:736)
	at com.intellij.psi.impl.ScopedClassHierarchy.calcImmediateSupersWithCapturing(ScopedClassHierarchy.java:189)
	at com.intellij.psi.impl.ScopedClassHierarchy.access$200(ScopedClassHierarchy.java:47)
	at com.intellij.psi.impl.ScopedClassHierarchy$4.compute(ScopedClassHierarchy.java:171)
	at com.intellij.psi.impl.ScopedClassHierarchy$4.compute(ScopedClassHierarchy.java:168)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.ScopedClassHierarchy.getImmediateSupersWithCapturing(ScopedClassHierarchy.java:168)
	at com.intellij.psi.impl.PsiClassImplUtil.getScopeCorrectedSuperTypes(PsiClassImplUtil.java:740)
	at com.intellij.psi.impl.PsiClassImplUtil.processSuperTypes(PsiClassImplUtil.java:750)
	at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClassNotCached(PsiClassImplUtil.java:721)
	at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClass(PsiClassImplUtil.java:484)
	at com.intellij.psi.impl.PsiClassImplUtil.access$700(PsiClassImplUtil.java:63)
	at com.intellij.psi.impl.PsiClassImplUtil$3.process(PsiClassImplUtil.java:724)
	at com.intellij.psi.impl.PsiClassImplUtil$3.process(PsiClassImplUtil.java:721)
	at com.intellij.psi.impl.PsiClassImplUtil.processSuperTypes(PsiClassImplUtil.java:755)
	at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClassNotCached(PsiClassImplUtil.java:721)
	at com.intellij.psi.impl.PsiClassImplUtil.access$500(PsiClassImplUtil.java:63)
	at com.intellij.psi.impl.PsiClassImplUtil$MembersMap.create(PsiClassImplUtil.java:405)
	at com.intellij.psi.impl.PsiClassImplUtil$MembersMap.create(PsiClassImplUtil.java:353)
	at com.intellij.util.containers.FactoryMap.get(FactoryMap.java:57)
	at com.intellij.psi.impl.PsiClassImplUtil.processCachedMembersByName(PsiClassImplUtil.java:558)
	at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClass(PsiClassImplUtil.java:481)
	at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClass(PsiClassImplUtil.java:458)
	at com.intellij.psi.impl.source.PsiClassImpl.processDeclarations(PsiClassImpl.java:491)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:69)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:51)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:218)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:149)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:458)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:55)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:360)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:352)
	at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:191)
	at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:188)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:188)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:754)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.getCanonicalText(PsiJavaCodeReferenceElementImpl.java:287)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.getCanonicalText(PsiJavaCodeReferenceElementImpl.java:272)
	at com.intellij.psi.impl.source.tree.java.PsiAnnotationImpl.getQualifiedName(PsiAnnotationImpl.java:96)
	at de.plushnikov.intellij.plugin.util.PsiAnnotationUtil.collectAnnotationsToCopy(PsiAnnotationUtil.java:141)
	at de.plushnikov.intellij.plugin.processor.field.AbstractFieldProcessor.copyAnnotations(AbstractFieldProcessor.java:84)
	at de.plushnikov.intellij.plugin.processor.field.GetterFieldProcessor.createGetterMethod(GetterFieldProcessor.java:138)
	at de.plushnikov.intellij.plugin.processor.clazz.GetterProcessor.createFieldGetters(GetterProcessor.java:80)
	at de.plushnikov.intellij.plugin.processor.clazz.GetterProcessor.generatePsiElements(GetterProcessor.java:71)
	at de.plushnikov.intellij.plugin.processor.clazz.AbstractClassProcessor.process(AbstractClassProcessor.java:57)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider$LombokCachedValueProvider.compute(LombokAugmentProvider.java:176)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:137)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:65)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:130)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.getAugments(LombokAugmentProvider.java:127)
	at com.intellij.psi.augment.PsiAugmentProvider$1.process(PsiAugmentProvider.java:95)
	at com.intellij.psi.augment.PsiAugmentProvider$1.process(PsiAugmentProvider.java:92)
	at com.intellij.psi.augment.PsiAugmentProvider.forEach(PsiAugmentProvider.java:146)
	at com.intellij.psi.augment.PsiAugmentProvider.collectAugments(PsiAugmentProvider.java:92)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.getAllMethods(ClassInnerStuffCache.java:174)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.access$300(ClassInnerStuffCache.java:39)
	at com.intellij.psi.impl.source.ClassInnerStuffCache$3.compute(ClassInnerStuffCache.java:79)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:137)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:65)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:130)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.getMethods(ClassInnerStuffCache.java:75)
	at com.intellij.psi.impl.source.PsiClassImpl.getMethods(PsiClassImpl.java:301)
	at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClassNotCached(PsiClassImplUtil.java:686)
	at com.intellij.psi.impl.PsiClassImplUtil.access$500(PsiClassImplUtil.java:63)
	at com.intellij.psi.impl.PsiClassImplUtil$MembersMap.create(PsiClassImplUtil.java:405)
	at com.intellij.psi.impl.PsiClassImplUtil$MembersMap.create(PsiClassImplUtil.java:353)
	at com.intellij.util.containers.FactoryMap.get(FactoryMap.java:57)
	at com.intellij.psi.impl.PsiClassImplUtil.processCachedMembersByName(PsiClassImplUtil.java:589)
	at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClass(PsiClassImplUtil.java:481)
	at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClass(PsiClassImplUtil.java:458)
	at com.intellij.psi.impl.source.PsiClassImpl.processDeclarations(PsiClassImpl.java:491)
	at com.intellij.psi.scope.util.PsiScopesUtil.a(PsiScopesUtil.java:497)
	at com.intellij.psi.scope.util.PsiScopesUtil.a(PsiScopesUtil.java:453)
	at com.intellij.psi.scope.util.PsiScopesUtil.setupAndRunProcessor(PsiScopesUtil.java:359)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.resolveToMethod(PsiReferenceExpressionImpl.java:300)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.resolve(PsiReferenceExpressionImpl.java:285)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.access$000(PsiReferenceExpressionImpl.java:61)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolve(PsiReferenceExpressionImpl.java:197)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolve(PsiReferenceExpressionImpl.java:186)
	at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:191)
	at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:188)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:188)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:754)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:743)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.multiResolve(PsiReferenceExpressionImpl.java:346)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionBase.advancedResolve(PsiReferenceExpressionBase.java:86)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionBase.resolve(PsiReferenceExpressionBase.java:48)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.resolveMethod(PsiMethodCallExpressionImpl.java:60)
	at com.intellij.spring.web.mvc.SpringControllerClassInfo$2.visitElement(SpringControllerClassInfo.java:193)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.accept(PsiMethodCallExpressionImpl.java:145)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:81)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at com.intellij.spring.web.mvc.SpringControllerClassInfo$2.visitElement(SpringControllerClassInfo.java:202)
	at com.intellij.psi.impl.source.tree.java.PsiExpressionListImpl.accept(PsiExpressionListImpl.java:145)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:81)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at com.intellij.spring.web.mvc.SpringControllerClassInfo$2.visitElement(SpringControllerClassInfo.java:202)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.accept(PsiMethodCallExpressionImpl.java:145)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:81)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at com.intellij.spring.web.mvc.SpringControllerClassInfo$2.visitElement(SpringControllerClassInfo.java:202)
	at com.intellij.psi.impl.source.tree.java.PsiLocalVariableImpl.accept(PsiLocalVariableImpl.java:287)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:81)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at com.intellij.spring.web.mvc.SpringControllerClassInfo$2.visitElement(SpringControllerClassInfo.java:202)
	at com.intellij.psi.impl.source.tree.java.PsiDeclarationStatementImpl.accept(PsiDeclarationStatementImpl.java:92)
	at com.intellij.psi.impl.source.tree.LazyParseablePsiElement.acceptChildren(LazyParseablePsiElement.java:106)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at com.intellij.spring.web.mvc.SpringControllerClassInfo$2.visitElement(SpringControllerClassInfo.java:202)
	at com.intellij.psi.impl.source.tree.java.PsiCodeBlockImpl.accept(PsiCodeBlockImpl.java:205)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:81)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at com.intellij.spring.web.mvc.SpringControllerClassInfo$2.visitElement(SpringControllerClassInfo.java:202)
	at com.intellij.psi.impl.source.tree.java.PsiTryStatementImpl.accept(PsiTryStatementImpl.java:167)
	at com.intellij.psi.impl.source.tree.LazyParseablePsiElement.acceptChildren(LazyParseablePsiElement.java:106)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at com.intellij.spring.web.mvc.SpringControllerClassInfo$2.visitElement(SpringControllerClassInfo.java:202)
	at com.intellij.psi.impl.source.tree.java.PsiCodeBlockImpl.accept(PsiCodeBlockImpl.java:205)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:200)
	at com.intellij.psi.impl.source.JavaStubPsiElement.acceptChildren(JavaStubPsiElement.java:168)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at com.intellij.spring.web.mvc.SpringControllerClassInfo$2.visitElement(SpringControllerClassInfo.java:202)
	at com.intellij.spring.web.mvc.SpringControllerClassInfo.visitMethod(SpringControllerClassInfo.java:338)
	at com.intellij.spring.web.mvc.SpringControllerClassInfo.computeVariables(SpringControllerClassInfo.java:208)
	at com.intellij.spring.web.mvc.SpringControllerClassInfo.lambda$getVariables$0(SpringControllerClassInfo.java:157)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:137)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:65)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:130)
	at com.intellij.spring.web.mvc.SpringControllerClassInfo.getVariables(SpringControllerClassInfo.java:157)
	at com.intellij.spring.web.mvc.model.SpringMVCModelImpl.processVariables(SpringMVCModelImpl.java:216)
	at com.intellij.spring.web.mvc.jsp.SpringMvcElVariablesProvider.processVariables(SpringMvcElVariablesProvider.java:59)
	at com.intellij.spring.web.mvc.jsp.SpringMvcElVariablesProvider.processImplicitVariables(SpringMvcElVariablesProvider.java:51)
	at com.intellij.psi.impl.source.jsp.el.impl.ELResolveUtil.processEmptyContext(ELResolveUtil.java:867)
	at com.intellij.psi.impl.source.jsp.el.impl.ELResolveUtil.process(ELResolveUtil.java:715)
	at com.intellij.psi.impl.source.jsp.el.impl.ELResolveUtil.resolveElement(ELResolveUtil.java:239)
	at com.intellij.psi.impl.source.jsp.el.impl.ELReference.resolveInner(ELReference.java:288)
	at com.intellij.psi.impl.source.jsp.el.impl.ELReference.access$200(ELReference.java:60)
	at com.intellij.psi.impl.source.jsp.el.impl.ELReference$MyResolver.resolve(ELReference.java:578)
	at com.intellij.psi.impl.source.jsp.el.impl.ELReference$MyResolver.resolve(ELReference.java:572)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:144)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
	at com.intellij.psi.impl.source.jsp.el.impl.ELReference.multiResolve(ELReference.java:492)
	at com.intellij.codeInspection.jsp.ELValidationInspection.checkVariableReference(ELValidationInspection.java:113)
	at com.intellij.codeInspection.jsp.ELValidationInspection.visitVariable(ELValidationInspection.java:106)
	at com.intellij.codeInspection.jsp.ELValidationInspection$1.visitELVariable(ELValidationInspection.java:74)
	at com.intellij.psi.impl.source.jsp.el.impl.ELVariableImpl.accept(ELVariableImpl.java:20)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:69)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:280)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:249)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:123)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1061)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:91)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by mplushnikov** [comment] 2018-01-14 13:36
I'll close it as duplicate of #324

**Closed by mplushnikov** 2018-01-14 13:36 UTC
