### ISSUE TITLE
IntelliJ IDEA 2020.2 not supported

### ISSUE THREAD

**Issue by finsterwalder** [mplushnikov/lombok-intellij-plugin#884] opened 2020-08-13 16:24 UTC
### Short description
When trying to update to IntelliJ IDEA 2020.2, I'm informed, that the Lombok Plugin is not supported.

### Expected behavior
Plugin works after Upgrade to 2020.2.

### Version information

 * **IDEA Version:** IntelliJ IDEA 2020.1.4 (Community Edition)
Build #IC-201.8743.12, built on July 21, 2020
Runtime version: 11.0.7+10-b765.65 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
 * **Lombok Plugin Version:** 0.30-2020.1

**Comment by OneCricketeer** [comment] 2020-08-13 16:58
#829

**Comment by mplushnikov** [comment] 2020-08-13 17:10
Closed as duplicate of #840 and #829

**Closed by mplushnikov** 2020-08-13 17:10 UTC
