### ISSUE TITLE
Compilation fails with Intellij 14.1.5

### ISSUE THREAD

**Issue by looztra** [mplushnikov/lombok-intellij-plugin#146] opened 2015-10-14 17:40 UTC
Context:
- Intellij 14.1.5
- Lombok plugin: 0.9.6.14

Issue:
- everything is fine in the editor view : 
  - no warning
  - lombok processing is fine (for instance, @Getter produces usable getter in other class, ...)
- but compilation fails (build project/compile class) as if the annotation processing is not taken into account in the compile phase

Sample class:

```java
package net.devlab722;

import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public class Lombi {

    private final String first;
    private final String second;
}
```

The logs:

```
/home/cfurmaniak/workspace/SANDBOXES/grokking-algorithms/src/main/java/net/devlab722/Lombi.java
Error:(8, 26) java: variable first not initialized in the default constructor
Error:(9, 26) java: variable second not initialized in the default constructor
```

**Comment by Janmm14** [comment] 2015-10-14 21:09
Did you enabled annotation processing in the options of intellij?

**Comment by looztra** [comment] 2015-10-15 05:51
Yes, with or without it, same failure result.

**Comment by mplushnikov** [comment] 2015-10-20 15:51
What is your jdk version? Are you using javac or eclipse compiler or something else?

**Comment by looztra** [comment] 2015-10-20 19:28
```
Information:Using javac 1.8.0_60 to compile java sources
```

```
└> java -version
openjdk version "1.8.0_60"
OpenJDK Runtime Environment (build 1.8.0_60-b27)
OpenJDK 64-Bit Server VM (build 25.60-b23, mixed mode)
```

**Comment by mplushnikov** [comment] 2015-10-25 17:41
Can you verify it with oracle jdk please?

**Comment by looztra** [comment] 2015-10-28 10:38
ok, this is weird. I checked twice on 2 distincts setup before submiting the issue. And it failed on both setup.
On top of that, someone reported the same issue (twitter).

And now, on one of my 2 setups...it works.

I will check on my second setup tonight.

stay tune

**Comment by mplushnikov** [comment] 2015-11-01 22:11
Any new results? It should simple work:)

**Comment by Janmm14** [comment] 2015-11-02 11:04
@looztra

**Comment by looztra** [comment] 2015-11-02 18:57
It works on one setup and still doesn't work on my second setup. Still
investigating what is the difference in the environment.

Is it working for everybody else?

**Comment by mplushnikov** [comment] 2015-11-02 19:08
All my colleagues doesn't have any problems with compilation (both MacOs and Windows)
Please verify your compiler settings and the option "Enable annotation processing". If somebody has any issues, this was the root cause.
![image](https://cloud.githubusercontent.com/assets/1204509/10891304/69f764e8-819d-11e5-81e5-0384fd1cb70c.png)

**Comment by jsurls** [comment] 2015-11-04 23:12
I had the same issue as @looztra .. enabling annotation processing fixed it for me

**Comment by looztra** [comment] 2015-12-09 19:48
Just tried with the oracle JDK: same problem.

Tried with a fresh install of intellij 15: same problem (by fresh I mean I cleared the .IntelliJIdea15 directory in my home).

(and yes, annotation processins is enabled)

**Comment by looztra** [comment] 2015-12-09 20:01
ok, I think I get it, and I'm a bit ashamed I did not realize earlier that it was related to the project that I used for testing.
I used the same class during all my tests, but not always in the same project :(

The answer is that in the non working project there are these dependencies:

```xml
<dependency>
            <groupId>org.openjdk.jmh</groupId>
            <artifactId>jmh-core</artifactId>
            <version>${jmh.version}</version>
        </dependency>
        <dependency>
            <groupId>org.openjdk.jmh</groupId>
            <artifactId>jmh-generator-annprocess</artifactId>
            <version>${jmh.version}</version>
            <scope>provided</scope>
        </dependency>
       <dependency>
            <groupId>org.openjdk.jmh</groupId>
            <artifactId>jmh-generator-annprocess</artifactId>
            <version>${jmh.version}</version>
            <scope>provided</scope>
        </dependency>
```

Without these dep, it works, with it does not work and generates the errors mentionned in my bug report.

**Comment by mplushnikov** [comment] 2016-01-11 22:03
Interesting problem! JMH benchmark generator is based on annotation processor. It's possible, that they interfere each other.
I will close this issue now, because it seems to work now for you.

**Closed by mplushnikov** 2016-01-11 22:03 UTC

**Comment by vasiliy-poperekov** [comment] 2022-12-17 07:02
Was the same problem. I used gradle like this:
dependencies {
   ...
   implementation 'org.projectlombok:lombok'
}
But I needed to use:
dependencies {
   ...
   compileOnly 'org.projectlombok:lombok:1.18.24'
   annotationProcessor 'org.projectlombok:lombok:1.18.24'
}
Correct lombok dependency for you can find here: https://projectlombok.org/setup/gradle
