### ISSUE TITLE
IntelliJ error report: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation

### ISSUE THREAD

**Issue by smmckay** [mplushnikov/lombok-intellij-plugin#102] opened 2015-04-22 13:58 UTC
provider: de.plushnikov.intellij.plugin.provider.LombokAugmentProvider@ef3d607: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
    com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
        at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:854)
        at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:803)
        at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:787)
        at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:250)
        at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:238)
        at com.intellij.psi.stubs.StubIndex.process(StubIndex.java:76)
        at com.intellij.psi.stubs.StubIndex.process(StubIndex.java:95)
        at com.intellij.psi.stubs.StubIndexImpl.get(StubIndexImpl.java:227)
        at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:144)
        at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:134)
        at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.get(JavaFullClassNameIndex.java:48)
        at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.a(JavaFileManagerImpl.java:145)
        at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClass(JavaFileManagerImpl.java:129)
        at com.intellij.psi.impl.PsiElementFinderImpl.findClass(PsiElementFinderImpl.java:54)
        at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:99)
        at com.intellij.psi.impl.PsiElementFactoryImpl.createTypeByFQClassName(PsiElementFactoryImpl.java:411)
        at com.intellij.psi.PsiType.getTypeByName(PsiType.java:147)
        at com.intellij.psi.PsiType.getJavaLangObject(PsiType.java:159)
        at com.intellij.psi.impl.PsiClassImplUtil.getSuperTypes(PsiClassImplUtil.java:902)
        at com.intellij.psi.impl.source.PsiClassImpl.getSuperTypes(PsiClassImpl.java:249)
        at com.intellij.psi.impl.PsiClassImplUtil.a(PsiClassImplUtil.java:774)
        at com.intellij.psi.impl.PsiClassImplUtil.a(PsiClassImplUtil.java:709)
        at com.intellij.psi.impl.PsiClassImplUtil.a(PsiClassImplUtil.java:478)
        at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClass(PsiClassImplUtil.java:448)
        at com.intellij.psi.impl.source.PsiClassImpl.processDeclarations(PsiClassImpl.java:488)
        at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:72)
        at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:54)
        at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:215)
        at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:146)
        at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.a(PsiJavaCodeReferenceElementImpl.java:438)
        at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:55)
        at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:339)
        at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:331)
        at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:191)
        at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:188)
        at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
        at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:188)
        at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:767)
        at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:757)
        at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:366)
        at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:359)
        at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:328)
        at de.plushnikov.intellij.plugin.processor.ValProcessor.isVal(ValProcessor.java:92)
        at de.plushnikov.intellij.plugin.processor.ValProcessor.inferType(ValProcessor.java:106)
        at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.inferType(LombokAugmentProvider.java:122)
        at com.intellij.psi.augment.PsiAugmentProvider.getInferredType(PsiAugmentProvider.java:73)
        at com.intellij.psi.impl.source.PsiTypeElementImpl.e(PsiTypeElementImpl.java:80)
        at com.intellij.psi.impl.source.PsiTypeElementImpl.getType(PsiTypeElementImpl.java:74)
        at com.intellij.psi.impl.source.tree.JavaSharedImplUtil.getType(JavaSharedImplUtil.java:46)
        at com.intellij.psi.impl.source.tree.JavaSharedImplUtil.getType(JavaSharedImplUtil.java:42)
        at com.intellij.psi.impl.source.PsiParameterImpl.getType(PsiParameterImpl.java:195)
        at com.intellij.psi.util.MethodSignatureBackedByPsiMethod.create(MethodSignatureBackedByPsiMethod.java:88)
        at com.intellij.psi.util.MethodSignatureBackedByPsiMethod.create(MethodSignatureBackedByPsiMethod.java:71)
        at com.intellij.psi.impl.source.PsiMethodImpl$1.compute(PsiMethodImpl.java:316)
        at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:131)
        at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
        at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:200)
        at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
        at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:83)
        at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:127)
        at com.intellij.psi.impl.source.PsiMethodImpl.getSignature(PsiMethodImpl.java:312)
        at com.intellij.ide.structureView.impl.AddAllMembersProcessor.b(AddAllMembersProcessor.java:82)
        at com.intellij.ide.structureView.impl.AddAllMembersProcessor.execute(AddAllMembersProcessor.java:53)
        at com.intellij.psi.impl.PsiClassImplUtil.a(PsiClassImplUtil.java:681)
        at com.intellij.psi.impl.PsiClassImplUtil.a(PsiClassImplUtil.java:478)
        at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClass(PsiClassImplUtil.java:448)
        at com.intellij.psi.impl.source.PsiClassImpl.processDeclarations(PsiClassImpl.java:488)
        at com.intellij.ide.structureView.impl.java.JavaInheritedMembersNodeProvider.provideNodes(JavaInheritedMembersNodeProvider.java:39)
        at com.intellij.ide.util.treeView.smartTree.TreeElementWrapper.initChildren(TreeElementWrapper.java:60)
        at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.b(CachingChildrenTreeNode.java:203)
        at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.a(CachingChildrenTreeNode.java:51)
        at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.getChildren(CachingChildrenTreeNode.java:44)
        at com.intellij.ide.structureView.newStructureView.StructureViewComponent$StructureViewTreeElementWrapper.getChildren(StructureViewComponent.java:838)
        at com.intellij.ide.util.treeView.smartTree.SmartTreeStructure.getChildElements(SmartTreeStructure.java:55)
        at com.intellij.ide.util.treeView.AbstractTreeUi$32.perform(AbstractTreeUi.java:1624)
        at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
        at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1830)
        at com.intellij.ide.util.treeView.AbstractTreeUi.getChildrenFor(AbstractTreeUi.java:1621)
        at com.intellij.ide.util.treeView.AbstractTreeUi.access$4700(AbstractTreeUi.java:62)
        at com.intellij.ide.util.treeView.AbstractTreeUi$31.perform(AbstractTreeUi.java:1546)
        at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
        at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1830)
        at com.intellij.ide.util.treeView.AbstractTreeUi.processUnbuilt(AbstractTreeUi.java:1533)
        at com.intellij.ide.util.treeView.AbstractTreeUi.doUpdateChildren(AbstractTreeUi.java:1259)
        at com.intellij.ide.util.treeView.AbstractTreeUi.access$3100(AbstractTreeUi.java:62)
        at com.intellij.ide.util.treeView.AbstractTreeUi$26$1.perform(AbstractTreeUi.java:1182)
        at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
        at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1830)
        at com.intellij.ide.util.treeView.AbstractTreeUi.access$2500(AbstractTreeUi.java:62)
        at com.intellij.ide.util.treeView.AbstractTreeUi$26.perform(AbstractTreeUi.java:1179)
        at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
        at com.intellij.openapi.util.ExecutionCallback.doWhenExecuted(ExecutionCallback.java:101)
        at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:108)
        at com.intellij.ide.util.treeView.AbstractTreeUi.updateNodeChildren(AbstractTreeUi.java:1174)
        at com.intellij.ide.util.treeView.AbstractTreeUi.updateNodesToInsert(AbstractTreeUi.java:1676)
        at com.intellij.ide.util.treeView.AbstractTreeUi.access$4300(AbstractTreeUi.java:62)
        at com.intellij.ide.util.treeView.AbstractTreeUi$30$2.consume(AbstractTreeUi.java:1404)
        at com.intellij.ide.util.treeView.AbstractTreeUi$30$2.consume(AbstractTreeUi.java:1400)
        at com.intellij.openapi.util.AsyncResult$2.run(AsyncResult.java:98)
        at com.intellij.openapi.util.ExecutionCallback.doWhenExecuted(ExecutionCallback.java:101)
        at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:108)
        at com.intellij.openapi.util.AsyncResult.doWhenDone(AsyncResult.java:95)
        at com.intellij.ide.util.treeView.AbstractTreeUi$30.perform(AbstractTreeUi.java:1399)
        at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
        at com.intellij.openapi.util.ExecutionCallback.setExecuted(ExecutionCallback.java:59)
        at com.intellij.openapi.util.ActionCallback.setDone(ActionCallback.java:69)
        at com.intellij.openapi.util.ActionCallback$3.run(ActionCallback.java:233)
        at com.intellij.openapi.util.ExecutionCallback.doWhenExecuted(ExecutionCallback.java:101)
        at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:108)
        at com.intellij.openapi.util.ActionCallback.notify(ActionCallback.java:153)
        at com.intellij.ide.util.treeView.AbstractTreeUi$34.perform(AbstractTreeUi.java:1783)
        at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
        at com.intellij.ide.util.treeView.AbstractTreeUi.executeYieldingRequest(AbstractTreeUi.java:2091)
        at com.intellij.ide.util.treeView.AbstractTreeUi.access$5900(AbstractTreeUi.java:62)
        at com.intellij.ide.util.treeView.AbstractTreeUi$38$1.perform(AbstractTreeUi.java:1983)
        at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
        at com.intellij.ide.util.treeView.AbstractTreeBuilder.runOnYeildingDone(AbstractTreeBuilder.java:433)
        at com.intellij.ide.util.treeView.AbstractTreeUi.runOnYieldingDone(AbstractTreeUi.java:2186)
        at com.intellij.ide.util.treeView.AbstractTreeUi$38.perform(AbstractTreeUi.java:1978)
        at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
        at com.intellij.ide.util.treeView.AbstractTreeBuilder$1.process(AbstractTreeBuilder.java:53)
        at com.intellij.ide.util.treeView.AbstractTreeBuilder$1.process(AbstractTreeBuilder.java:50)
        at com.intellij.util.containers.TransferToEDTQueue.processNext(TransferToEDTQueue.java:98)
        at com.intellij.util.containers.TransferToEDTQueue.access$300(TransferToEDTQueue.java:36)
        at com.intellij.util.containers.TransferToEDTQueue$1.run(TransferToEDTQueue.java:57)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:702)
        at java.awt.EventQueue$3.run(EventQueue.java:696)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
        at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

I have no idea what IntelliJ is complaining about but it seems to feel strongly about this matter.

**Comment by mplushnikov** [comment] 2015-04-25 21:08
Duplicate of #98

**Closed by mplushnikov** 2015-04-25 21:08 UTC
Labels: duplicate
