### ISSUE TITLE
IDE highlights val as an error if it had reparsed code before the line was completed

### ISSUE THREAD

**Issue by GloomyFolken** [mplushnikov/lombok-intellij-plugin#142] opened 2015-10-02 11:23 UTC
Intellij IDEA reparses code to highlight errors 300 ms after the last character was typed (this delay can be changed in Settings -> Editor -> General -> Autoreparse delay). If user stops typing after something like "val foo =", IDE will reparse code and highlight val. However, val still will be highlighted after the line is completed. So, the only way to use val is to increase autoreparse delay.
![0](https://cloud.githubusercontent.com/assets/4989473/10245522/e07468f0-6910-11e5-81a9-39cdd61a4f76.png)
![default](https://cloud.githubusercontent.com/assets/4989473/10245523/e2a63310-6910-11e5-9ec2-125ff002a70e.png)

**Comment by mplushnikov** [comment] 2015-11-02 13:20
@akozlova Maybe you can give me a hint, how we can solve this kind of problem?

**Comment by akozlova** [comment] 2015-11-02 13:55
That's a core problem, caused by cached type inside PsiTypeElementImpl. We are working on it. Thanks

**Comment by mplushnikov** [comment] 2015-11-02 15:31
Great! Do you have some issue number to track the progress in youtrack.jetbrains.com?

**Comment by akozlova** [comment] 2015-11-02 16:12
There are a number of exceptions, youtrack issue is welcome

**Comment by mplushnikov** [comment] 2015-11-02 18:38
Ok, I'll create some issues in Youtrack.
https://youtrack.jetbrains.com/issue/IDEA-147214

**Comment by mplushnikov** [comment] 2016-01-12 13:42
Jetbrains guys means: It is fixed in builds 144.839, 143.708  of IntelliJ

**Comment by mplushnikov** [comment] 2016-02-01 22:33
Looks to work very well with IntelliJ 15.0.3!

**Closed by mplushnikov** 2016-02-01 22:33 UTC
Labels: needIntelliJSupport

**Comment by leduold** [comment] 2016-02-02 03:56
@mplushnikov IntelliJ 15.0.3 has the problem too.......................

**Comment by akozlova** [comment] 2016-02-02 07:18
please provide details in IDEA's issue. Thanks
