### ISSUE TITLE
Lombok plugin with Intellij Ultimate Edition 2016.1.2 throwing error

### ISSUE THREAD

**Issue by Sandhyakripalani** [mplushnikov/lombok-intellij-plugin#293] opened 2016-10-05 08:06 UTC
PSI and index do not match
Please report the problem to JetBrains with the file attached
 file=PsiJavaFile:UnparsedNotification.java, file.class=class com.intellij.psi.impl.source.PsiJavaFileImpl, file.lang=Language: JAVA, modStamp=0
 tree consistent
 stub debugInfo=created in getStubTree(), no AST; with backReference
 document before=null
latestIndexedStub=null
 viewProvider=SingleRootFileViewProvider{myVirtualFile=jar://C:/Users/t_sandhyak/.m2/repository/com/google/api-client/google-api-client/1.17.0-rc/google-api-client-1.17.0-rc-sources.jar!/com/google/api/client/googleapis/notifications/UnparsedNotification.java, content=VirtualFileContent{size=4541}}
 viewProvider stamp: 0; file stamp: 0; file modCount: 1473745756703; file length: 4541
 doc saved: true; doc stamp: 0; doc size: 4541; committed: true
in many projects: false
indexing info: no data
java.lang.Throwable
    at com.intellij.psi.impl.DebugUtil.currentStackTrace(DebugUtil.java:501)
    at com.intellij.psi.stubs.StubProcessingHelper.stubTreeAndIndexDoNotMatch(StubProcessingHelper.java:43)
    at com.intellij.psi.stubs.StubProcessingHelperBase.a(StubProcessingHelperBase.java:175)
    at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:165)
    at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:52)
    at com.intellij.psi.stubs.StubIndexImpl$1.process(StubIndexImpl.java:232)
    at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:593)
    at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:581)
    at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:81)
    at com.intellij.psi.stubs.StubIndexImpl.a(StubIndexImpl.java:258)
    at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:224)
    at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:145)
    at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:135)
    at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.get(JavaFullClassNameIndex.java:48)
    at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClasses(JavaFileManagerImpl.java:78)
    at com.intellij.psi.impl.PsiElementFinderImpl.findClasses(PsiElementFinderImpl.java:60)
    at com.intellij.psi.impl.JavaPsiFacadeImpl.findClasses(JavaPsiFacadeImpl.java:166)
    at com.intellij.psi.impl.file.PsiPackageImpl.c(PsiPackageImpl.java:211)
    at com.intellij.psi.impl.file.PsiPackageImpl.findClassByShortName(PsiPackageImpl.java:277)
    at com.intellij.psi.impl.file.PsiPackageImpl.processDeclarations(PsiPackageImpl.java:325)
    at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:218)
    at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:154)
    at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.a(PsiJavaCodeReferenceElementImpl.java:443)
    at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:55)
    at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:344)
    at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:336)
    at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:191)
    at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:188)
    at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:188)
    at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:766)
    at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:755)
    at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:371)
    at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:364)
    at com.intellij.psi.impl.source.PsiClassReferenceType.resolveGenerics(PsiClassReferenceType.java:145)
    at com.intellij.psi.PsiClassType.isRaw(PsiClassType.java:202)
    at com.intellij.psi.PsiIntersectionType.flatten(PsiIntersectionType.java:97)
    at com.intellij.psi.PsiIntersectionType$1.compute(PsiIntersectionType.java:67)
    at com.intellij.psi.PsiIntersectionType$1.compute(PsiIntersectionType.java:64)
    at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
    at com.intellij.psi.PsiIntersectionType.flattenAndRemoveDuplicates(PsiIntersectionType.java:64)
    at com.intellij.psi.PsiIntersectionType.createIntersection(PsiIntersectionType.java:56)
    at com.intellij.psi.PsiIntersectionType.createIntersection(PsiIntersectionType.java:49)
    at com.intellij.psi.GenericsUtil.getGreatestLowerBound(GenericsUtil.java:44)
    at com.intellij.psi.impl.source.resolve.PsiOldInferenceHelper.a(PsiOldInferenceHelper.java:778)
    at com.intellij.psi.impl.source.resolve.PsiOldInferenceHelper.a(PsiOldInferenceHelper.java:424)
    at com.intellij.psi.impl.source.resolve.PsiOldInferenceHelper.inferTypeArguments(PsiOldInferenceHelper.java:283)
    at com.intellij.psi.impl.source.resolve.PsiResolveHelperImpl.inferTypeArguments(PsiResolveHelperImpl.java:190)
    at com.intellij.psi.infos.MethodCandidateInfo$4.compute(MethodCandidateInfo.java:396)
    at com.intellij.psi.infos.MethodCandidateInfo$4.compute(MethodCandidateInfo.java:381)
    at com.intellij.psi.infos.MethodCandidateInfo.computeForOverloadedCandidate(MethodCandidateInfo.java:251)
    at com.intellij.psi.infos.MethodCandidateInfo.inferTypeArguments(MethodCandidateInfo.java:381)
    at com.intellij.psi.infos.MethodCandidateInfo.inferTypeArguments(MethodCandidateInfo.java:360)
    at com.intellij.psi.infos.MethodCandidateInfo.getSubstitutor(MethodCandidateInfo.java:295)
    at com.intellij.psi.infos.MethodCandidateInfo.getSubstitutor(MethodCandidateInfo.java:278)
    at com.intellij.psi.PsiDiamondTypeImpl$1.compute(PsiDiamondTypeImpl.java:165)
    at com.intellij.psi.PsiDiamondTypeImpl$1.compute(PsiDiamondTypeImpl.java:150)
    at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
    at com.intellij.psi.PsiDiamondTypeImpl.resolveInferredTypesNoCheck(PsiDiamondTypeImpl.java:150)
    at com.intellij.psi.PsiDiamondTypeImpl.resolveInferredTypes(PsiDiamondTypeImpl.java:135)
    at com.intellij.psi.PsiDiamondTypeImpl.resolveInferredTypes(PsiDiamondTypeImpl.java:117)
    at com.intellij.psi.PsiDiamondTypeImpl.resolveInferredTypes(PsiDiamondTypeImpl.java:113)
    at com.intellij.psi.impl.PsiImplUtil.typesByTypeElements(PsiImplUtil.java:266)
    at com.intellij.psi.impl.PsiImplUtil.typesByReferenceParameterList(PsiImplUtil.java:256)
    at com.intellij.psi.impl.source.tree.java.PsiReferenceParameterListImpl.getTypeArguments(PsiReferenceParameterListImpl.java:49)
    at com.intellij.psi.impl.PsiDiamondTypeUtil.a(PsiDiamondTypeUtil.java:263)
    at com.intellij.psi.impl.PsiDiamondTypeUtil.areTypeArgumentsRedundant(PsiDiamondTypeUtil.java:206)
    at com.intellij.psi.impl.PsiDiamondTypeUtil.a(PsiDiamondTypeUtil.java:80)
    at com.intellij.psi.impl.PsiDiamondTypeUtil.canCollapseToDiamond(PsiDiamondTypeUtil.java:45)
    at com.intellij.codeInspection.ExplicitTypeCanBeDiamondInspection$1.visitNewExpression(ExplicitTypeCanBeDiamondInspection.java:69)
    at de.plushnikov.intellij.plugin.inspection.LombokExplicitTypeCanBeDiamondInspection$1.visitNewExpression(LombokExplicitTypeCanBeDiamondInspection.java:27)
    at com.intellij.psi.impl.source.tree.java.PsiNewExpressionImpl.accept(PsiNewExpressionImpl.java:382)
    at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:320)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:315)
    at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:128)
    at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
    at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:91)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
    at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:100)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:112)
    at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:88)
    at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)

**Comment by Sandhyakripalani** [comment] 2016-10-05 08:09
This is a fatal error thrown by the IDE 
![lombokpluginerror](https://cloud.githubusercontent.com/assets/10030011/19105719/19917318-8b01-11e6-953f-949fd40b2931.png)

**Comment by mplushnikov** [comment] 2018-01-14 13:38
I'll close it as duplicate of #324

**Closed by mplushnikov** 2018-01-14 13:38 UTC
Labels: PSI and Index
