### ISSUE TITLE
Support @UtilityClass

### ISSUE THREAD

**Issue by bannmann-incub8** [mplushnikov/lombok-intellij-plugin#188] opened 2016-02-19 08:13 UTC
When I use Lombok's [UtilityClass annotation](https://projectlombok.org/features/experimental/UtilityClass.html), all members are automatically static. However, although the compilation works perfectly, IntelliJ complains every time I invoke any method of that class:

> non-static method X cannot be referenced from a static context

When I redundantly add the `static` modifier myself, the errors disappear.

**Comment by mkochenough** [comment] 2016-02-19 08:25
This is duplicate of https://github.com/mplushnikov/lombok-intellij-plugin/issues/143 and should get closed.

**Comment by bannmann-incub8** [comment] 2016-02-19 08:48
Ah, turns out I was wrong to assume searching for "utility" would list duplicates: seems like GitHub issue search does not implement partial matching.

**Closed** 2016-02-19 13:42 UTC
Labels: duplicate

**Comment by prashantverma999** [comment] 2016-11-02 18:56
#143 has not fixed this bug. This bug is still present, at least in the following version of the plugin:

    Lombok Plugin: 0.13.15 (link to changelog specifying support for UtilityClass)
    Intellij: v15.0.3 build #IU-143.1821
Can this issue be re-opened?
