### ISSUE TITLE
ProcessCanceledException when opening project

### ISSUE THREAD

**Issue by akazancev** [mplushnikov/lombok-intellij-plugin#560] opened 2018-11-28 21:06 UTC
### Short description
Lombok plugin causes exceptions to be thrown when opening the project caused by JavaPsiFacadeImpl.findPackage call from project component.

### Expected behavior
No exceptions thrown
According to Peter Gromov
"I think Lombok plugin should deal with it. Ideally, it shouldn't call findPackage from UI thread on startup, as this call can be quite slow at times. It should do all PSI-accessing activities on a cancellable background thread, then it won't have to do anything special for this PCE."

### Version information
IntelliJ IDEA 2018.2.6 (Ultimate Edition)
Build #IU-182.5107.16, built on November 6, 2018
Licensed to LinkedIn Corporation

JRE: 1.8.0_152-release-1248-b22 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6 
Lombok Plugin (0.21.2018.2)

### Steps to reproduce
The issue is intermittent
more details here https://youtrack.jetbrains.com/issue/IDEA-201432
### Stacktrace

```

java.lang.Throwable: Control-flow exceptions (like ProcessCanceledException) should never be logged
 at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:102)
 at com.intellij.openapi.diagnostic.Logger.error(Logger.java:149)
 at com.intellij.openapi.project.impl.ProjectManagerImpl.fireProjectOpened(ProjectManagerImpl.java:784)
 at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$null$6(ProjectManagerImpl.java:390)
 at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransactionAndWait$2(TransactionGuardImpl.java:165)
 at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
 at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
 at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
 at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
 at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
 at java.awt.EventQueue.access$500(EventQueue.java:98)
 at java.awt.EventQueue$3.run(EventQueue.java:715)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
 at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
 at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
 at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
 at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:864)
 at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:205)
 at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:191)
 at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:588)
 at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:446)
 at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:109)
 at com.intellij.openapi.progress.impl.CoreProgressManager.runSynchronously(CoreProgressManager.java:318)
 at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:303)
 at com.intellij.openapi.progress.ProgressManager.run(ProgressManager.java:192)
 at com.intellij.openapi.project.impl.ProjectManagerImpl.loadAndOpenProject(ProjectManagerImpl.java:482)
    ...
Caused by: com.intellij.openapi.progress.ProcessCanceledException
 at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:738)
 at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:706)
 at com.intellij.psi.stubs.StubIndexImpl.doProcessStubs(StubIndexImpl.java:336)
 at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:312)
 at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:145)
 at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:134)
 at org.jetbrains.plugins.scala.lang.psi.stubs.index.ScalaIndexKeys$StubIndexKeyExt$.elements$extension(ScalaIndexKeys.scala:67)
 at org.jetbrains.plugins.scala.lang.psi.stubs.index.ScalaIndexKeys$StubIndexIntegerKeyExt$.integerElements$extension1(ScalaIndexKeys.scala:93)
 at org.jetbrains.plugins.scala.lang.psi.stubs.index.ScalaIndexKeys$StubIndexIntegerKeyExt$.integerElements$extension0(ScalaIndexKeys.scala:89)
 at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.synthetic.ScSyntheticPackage$.apply(ScSyntheticPackage.scala:83)
 at org.jetbrains.plugins.scala.lang.psi.impl.ScalaPsiManager.$anonfun$syntheticPackage$1(ScalaPsiManager.scala:291)
 at java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:324)
 at org.jetbrains.plugins.scala.lang.psi.impl.ScalaPsiManager.syntheticPackage(ScalaPsiManager.scala:291)
 at org.jetbrains.plugins.scala.finder.ScalaPackageFinder.findPackage(ScalaPackageFinder.scala:19)
 at com.intellij.psi.impl.JavaPsiFacadeImpl.findPackage(JavaPsiFacadeImpl.java:239)
 at de.plushnikov.intellij.plugin.LombokPluginProjectValidatorComponent.hasLombokLibrary(LombokPluginProjectValidatorComponent.java:118)
 at de.plushnikov.intellij.plugin.LombokPluginProjectValidatorComponent.projectOpened(LombokPluginProjectValidatorComponent.java:61)
 at com.intellij.openapi.project.impl.ProjectManagerImpl.fireProjectOpened(ProjectManagerImpl.java:781)
 ... 75 more

```

**Comment by mplushnikov** [comment] 2018-12-20 13:40
Thank you @akazancev I'll apply suggestions from youtrack ticket.

**Comment by mplushnikov** [comment] 2018-12-20 13:42
Duplicate of #300

**Comment by akazancev** [comment] 2018-12-22 02:36
@mplushnikov you are most welcome, Thank you for taking care about this!

**Closed** 2019-02-27 11:23 UTC
