### ISSUE TITLE
Missing Support for IntelliJ 2019.1

### ISSUE THREAD

**Issue by danielhammerl** [mplushnikov/lombok-intellij-plugin#606] opened 2019-03-29 16:08 UTC
This plugin is incompatible with the latest version of Intellij (2019.1)

**Comment by mkasberg** [comment] 2019-03-29 16:36
I was able to confirm that this plugin **does** work in IntelliJ IDEA 2019.1, _despite_ the warning you get when upgrading.

**Comment by mkasberg** [comment] 2019-03-29 16:38
Also, this appears to be a duplicate of #605, #604, #603, #583.

Maybe it would be good to leave this open for a day or two so people see it and know that it's safe to upgrade?

**Comment by yulimingchn** [comment] 2019-03-30 07:17
Upgraded Lombok plug-in can not use the problem, can modify the idea configuration folder, 
users\. IntelliJIdea 2019.1\ config\ plugins\ lombok-plugin\ lib \lombok-plugin-0.23-2018.3.jar, open with compression software, directly edit META-INF\ plugin.xml, Change Line 6 <idea-version since-build="183.4284" until-build="183.*"/> to <idea-version since-build= "183.4284" until-build= "191. *"/>, save it in jar, and restart IDEA. You need to recompile the project.

**Comment by JonmarkWeber** [comment] 2019-04-01 14:59
Our development team is running the latest version of this plugin and we are getting errors for `@FieldNameConstants` injected field name constants (sorry for the redundancy there):

![Screen Shot 2019-04-01 at 7 58 13 AM](https://user-images.githubusercontent.com/10508092/55337689-02a71080-5454-11e9-89eb-fd1031c07856.png)

Did a full code rebuild and everything compiles, but the errors persist.

**Comment by mplushnikov** [comment] 2019-04-01 16:18
plugin version 0.24 was released some days ago and should silently support IntelliJ 2019.1

**Closed by mplushnikov** 2019-04-01 16:18 UTC
Labels: duplicate
