### ISSUE TITLE
Issues with IDEA #IU-162.1121.32 and lombok plugin 0.13.16

### ISSUE THREAD

**Issue by jeffreyhilaire** [mplushnikov/lombok-intellij-plugin#275] opened 2016-07-31 01:16 UTC
Hello,

I have recently upgraded the lombok plugin to 0.13.16 after an earlier upgrade of IDEA 2016. Since I have done this upgrade I started experiencing random errors such as the ones listed below and a massive increase in memory usage by IDEA until it eventually crashes. I increased the available memory for IntelliJ from 512 MB ( which I have been using fine for months ) to 1024 MB but in a matter of hours I run out of memory just editing files ( not compiling or running any application ).

Throwable: Accessing 'java.class.fqn' during processing 'java.field.name'. Nested different indices processing may cause deadlock

I added the version for IDEA, JDK and the lombok plugin in case this helps.

[IDEA]
IntelliJ IDEA 2016.2
Build #IU-162.1121.32, built on July 9, 2016
JRE: 1.8.0_76-release-b216 x86
JVM: OpenJDK Server VM by JetBrains s.r.o

[lombok-plugin]
0.13.16

Jeffrey

**Comment by Janmm14** [comment] 2016-07-31 01:18
Maybe a duplicate of #261

**Comment by jeffreyhilaire** [comment] 2016-07-31 01:25
I have un-installed the plugin and installed it manually as others have done for #261 and see if this helps with the errors and the memory usage.

**Comment by AlexejK** [comment] 2016-08-10 12:56
as per my comment in #261, could you re-validate this with 2016.2.2 EAP?

**Closed** 2016-08-10 14:50 UTC
Labels: duplicate
