### ISSUE TITLE
Plugin "Lombok" is incompatible (until build 201.SNAPSHOT < IC-202.6397.94).

### ISSUE THREAD

**Issue by inthink** [mplushnikov/lombok-intellij-plugin#871] opened 2020-08-09 07:19 UTC
Plugin "Lombok" is incompatible (until build 201.SNAPSHOT < IC-202.6397.94).

IntelliJ IDEA 2020.2 (Community Edition)
Build #IC-202.6397.94, built on July 27, 2020
Runtime version: 11.0.7+10-b944.20 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.6
GC: ParNew, ConcurrentMarkSweep
Memory: 3683M
Cores: 8
Registry: ide.tree.collapse.recursively=false
Non-Bundled Plugins: CMD Support, String Manipulation, com.intellij.ideolog, com.dubreuia, io.github.qeesung.component.HighlightBracketPair, net.vektah.codeglance, ru.adelf.idea.dotenv, AliP3CPlugin, MavenRunHelper, zielu.gittoolbox, com.ccnode.codegenerator.MyBatisCodeHelperPro, izhangzhihao.rainbow.brackets

**Comment by mklueh** [comment] 2020-08-09 13:43
Same. 

Could somebody please explain why this incompatibilities can even happen?

What breaks the compatibility? Is it the IntelliJ API that changes?

**Comment by mklueh** [comment] 2020-08-09 13:46
Found the explanation here [https://github.com/mplushnikov/lombok-intellij-plugin/issues/859#issuecomment-667855337](https://github.com/mplushnikov/lombok-intellij-plugin/issues/859#issuecomment-667855337)

Seems to be indeed the Intellij API that has breaking changes introduced

**Comment by dmatthijssen** [comment] 2020-08-10 09:32
Please update the plugin, I haven't been able to use intellij properly for two weeks now :-)

**Comment by ruurd** [comment] 2020-08-11 09:54
> Please update the plugin, I haven't been able to use intellij properly for two weeks now :-)

Then search for other issues here. Maybe have a look at #840 and try the patched plugin.

**Comment by mplushnikov** [comment] 2020-08-12 18:27
Close as duplicate of #840

**Closed by mplushnikov** 2020-08-12 18:27 UTC
