### ISSUE TITLE
intellij objects to overriding builder methods when setterPrefix set

### ISSUE THREAD

**Issue by andifreed** [mplushnikov/lombok-intellij-plugin#825] opened 2020-06-25 21:53 UTC
### Short description

Builder treats the method with the same name as an override unless the overload is explicitly declared, but intellij objects to declaring the setter explicitly when the setterPrefix was used.  (Without setterPrefix and the methods changed to just the property name, was acceptable to intellij and Builder.

### Expected behavior

Intellij objects to the withSecret(byte[] value) declaration, says it already exists (and it the structure tab it has 3 overloads 2 with byte[]).  However, gradle builds and the tests fine.  Even running the tests in intellij also run.  It just that intellij flags those classes in error.

### Version information

 * **IDEA Version:** IntelliJ IDEA 2020.1.1 (Ultimate Edition)
Build #IU-201.7223.91, built on April 29, 2020
Non-Bundled Plugins: Batch Scripts Support, Lombook Plugin, org.jetbrains.plugins.spotbugs
 * **JDK Version:** 1.8.0_181
    classpath "io.freefair.gradle:lombok-plugin:5.1.0"
 * **OS Type & Version:** Windows 10 10.0
 * **Lombok Plugin Version:** 0.30-2020.1
 * **Lombok Dependency Version:** 1.18.12

### Steps to reproduce
_What steps do we need to take to reproduce this issue?_

open src/java/test/example/Secret.java

### Sample project

[bug.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/4833986/bug.zip)

 - [x] Sample project provided
 - [x] I am able to reproduce this error on the sample project by following the steps described above

### Additional information
_Is there any additional information you can provide to help us understanding and solving the issue?_

**Comment by mplushnikov** [comment] 2020-08-23 17:40
looks like duplicate of #760

**Closed** 2020-08-25 20:11 UTC
