### ISSUE TITLE
@Data annotation not recognized in IntelliJ 14.1.1 with JDK8

### ISSUE THREAD

**Issue by abeketovski** [mplushnikov/lombok-intellij-plugin#99] opened 2015-04-12 01:51 UTC
Just installed v0.9.2. Annotation processing is enabled. "Enable Lombok plugin" checkbox is checked as well. 

After restarting IDE, reloading the project and rebuilding annotation still shows as "Cannot resolve symbol".

IDE: IntelliJ IDEA 14.1.1
JRE: 1.8.9-b132 amd64

**Comment by mplushnikov** [comment] 2015-05-02 11:31
Can't reproduce any errors with @Data. Do you have some examples?
Can you verify it again with last Intellij and plugin version? What is your lombok version?

**Comment by JWGmeligMeyling** [comment] 2015-06-02 20:44
Have seen some errors from time to time with `@Data` as well. Switching to `@Getter` works fine.

Plugin: v0.9.4.14 
IntelliJ: 14.1.3
Java version: 1.8.0_20, vendor: Oracle Corporation
Apache Maven 3.3.1 (cab6659f9874fa96462afef40fcf6bc033d58c1c; 2015-03-13T21:10:27+01:00)
OSX 10.10.3

**Comment by txsmith** [comment] 2015-06-02 20:52
This happens to me too, right after I save a class annotated with @Data, the IDE gives no warnings. However, when I start editing another file, the warnings reappear and I have to manually save all my annotated classes again to suppress the warnings. Using @Getter or any other annotation does not work for me.

Ubuntu 14.04
Plugin version 0.9.4.14 
IntelliJ: 14.1.3 build 141.1010
JDK 1.8.0_45 Oracle

**Comment by mplushnikov** [comment] 2015-07-14 22:37
I can't reproduce it after 0.9.5 any more. Will close this issue as done. Feel free to open new issue, if you find the problem again.

**Closed by mplushnikov** 2015-07-14 22:37 UTC
Labels: bug

**Comment by JWGmeligMeyling** [comment] 2015-07-18 18:53
Can't reproduce it either! :+1:
