### ISSUE TITLE
val can not work when method has  Generic  return   

### ISSUE THREAD

**Issue by leduold** [mplushnikov/lombok-intellij-plugin#183] opened 2016-02-01 09:21 UTC
eg:

public <T> T convertMsg(string msg, int userMid){
     return (T) callAdapterMethod(string filed1,int field2);
}

the idea tell me unknow class when i call the method above

public void test(){
         val  msg=convertMsg("123",1);
}

**Comment by mplushnikov** [comment] 2016-02-01 18:19
Duplicate of #168

**Closed by mplushnikov** 2016-02-01 18:19 UTC
