### ISSUE TITLE
Wrong code structure is generated in 0.30-EAP

### ISSUE THREAD

**Issue by martinvisser** [mplushnikov/lombok-intellij-plugin#897] opened 2020-08-20 09:18 UTC
### Short description
Wrong code structure is generated in 0.30-EAP. As in wrong types or not at all.

### Expected behavior
Getters are generated with the correct type.

### Version information
IntelliJ IDEA 2020.2 (Ultimate Edition)
Build #IU-202.6397.94, built on July 27, 2020
Runtime version: 11.0.7+10-b944.20 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.6
 * **IDEA Version:** Build #IU-202.6397.94, built on July 27, 2020
 * **JDK Version:** 11.0.7+10-b944.20 x86_64
 * **OS Type & Version:** macOS 10.15.6
 * **Lombok Plugin Version:** 0.30-EAP
 * **Lombok Dependency Version:** 1.18.12

### Steps to reproduce
With this source:
```java
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.cloud.context.config.annotation.RefreshScope;
import org.springframework.stereotype.Component;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;

@Getter
@Setter
@ConfigurationProperties("app.cache")
@RefreshScope
@Component
public class CacheProperties {
    private final Map<String, Expiry> caches = new HashMap<>();

    private Duration connectTimeout;
    private Duration readTimeout;
    private Duration writeTimeout;

    @Getter
    @Setter
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Expiry {
        public static final Expiry DEFAULT = new Expiry(Duration.ofDays(1), Duration.ofMinutes(30));

        private Duration ttl;
        private Duration refresh;
    }
}
```
Removing `@Getter` and re-adding doesn't create any fields, moving fields around creates wrong types for fields. See screenshots.
1. Initial, correct structure: ![image](https://user-images.githubusercontent.com/3170236/90751006-dce30b80-e2d5-11ea-87fe-6f47e59aa6c2.png)
1. Moved the final field down results in wrong type(s): ![image](https://user-images.githubusercontent.com/3170236/90751266-321f1d00-e2d6-11ea-9766-52d205445409.png)
1. Different order, with other wrong type(s): ![image](https://user-images.githubusercontent.com/3170236/90751476-77dbe580-e2d6-11ea-972c-3b1e0f112686.png)

Also tried with moving the inner class to upper level, but it doesn't change the behaviour.
To be honest, I really have no idea what to provide more. So if anyone does, please ask.

**Comment by mplushnikov** [comment] 2020-08-20 09:47
Intellij 2020.2 is not compatible. Please update to IntelliJ IDEA 2020.2.1 RC Build #IC-202.6948.36, built on August 18, 2020
Closed as duplicate of #840 and #829

**Closed by mplushnikov** 2020-08-20 09:47 UTC
