### ISSUE TITLE
Most recent Intellij build - plugin doesn't work

### ISSUE THREAD

**Issue by the4yeast** [mplushnikov/lombok-intellij-plugin#251] opened 2016-06-22 04:41 UTC
Hi!

It looks like the plugin doesn't work on the most recent build of Intellij.

_IntelliJ IDEA 2016.2 EAP
Build #IU-162.1024.1, built on June 21, 2016
IntelliJ IDEA EAP User
Expiration date: July 21, 2016
JRE: 1.8.0_77-b03 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation_

I'm not sure whether it worked before, since I just started using the plugin today.

**Comment by AlexejK** [comment] 2016-06-22 04:47
Current released version of plugin works with released version of IDEA. 
We have already made improvements as well as compatibility changes in the latest codebase that should support 2016.2. The version of the plugin that will support it is 0.12, but it's not yet released. 

Please consider using 2016.1 for this plugin version  0.11 in the mean time. 

I will close this ticket for now. If you believe the issue is still present,  feel free to reopen.

**Closed by AlexejK** 2016-06-22 04:47 UTC
Labels: question

**Comment by the4yeast** [comment] 2016-06-22 04:51
Just in case you missed it (my apologies if you haven't) - it's yesterday's build, not the first in the 2016.2 family. Perhaps JetBrains made some change in there?

Otherwise, I'll just patiently wait for 0.12.

Thanks!

**Comment by AlexejK** [comment] 2016-06-22 05:02
Thanks,  we check against both trunk and EAPs :)  and yes,  they have made changes several times in the last few weeks that broke a lot of code.  Most of it is fixed though.

**Comment by the4yeast** [comment] 2016-06-22 05:11
Sounds good, thanks for clarifying!
