### ISSUE TITLE
Deadlock warning in intellij 2016.2

### ISSUE THREAD

**Issue by kmmanu** [mplushnikov/lombok-intellij-plugin#280] opened 2016-08-11 06:20 UTC
Accessing 'java.class.fqn' during processing 'java.field.name'. Nested different indices processing may cause deadlock

**Comment by AlexejK** [comment] 2016-08-11 07:46
Duplicate of #261 
As mentioned in that ticket - the fixes are rolled out in the latest versions of IDEA.

If you have tried this on 2016.2.2 EAP - Please provide your exact IntelliJ version, Lombok plugin version and Lombok dependency version.

**Closed** 2016-08-11 07:53 UTC
Labels: duplicate
