### ISSUE TITLE
Fatal Errors with 2017.1 EAP

### ISSUE THREAD

**Issue by IceMan81** [mplushnikov/lombok-intellij-plugin#349] opened 2017-01-27 19:13 UTC
Component name collision: UpdateComponent class de.plushnikov.intellij.plugin.LombokPluginUpdateProjectComponent and class 

```
Component name collision: UpdateComponent class de.plushnikov.intellij.plugin.LombokPluginUpdateProjectComponent and class mobi.hsz.idea.gitignore.UpdateComponent
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:432)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.access$300(ComponentManagerImpl.java:58)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:492)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:125)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:109)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:96)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:285)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:238)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.c(ProjectManagerImpl.java:472)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.access$100(ProjectManagerImpl.java:63)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$2.compute(ProjectManagerImpl.java:419)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$2.compute(ProjectManagerImpl.java:416)
	at com.intellij.openapi.progress.Task$WithResult.run(Task.java:324)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:757)
	at com.intellij.openapi.progress.impl.CoreProgressManager$11.run(CoreProgressManager.java:436)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:181)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:587)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:166)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:594)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:330)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by AlexejK** [comment] 2017-01-27 22:14
This is a duplicate of #337 which has been resolved in the HEAD.

**Closed by AlexejK** 2017-01-27 22:14 UTC

**Comment by IceMan81** [comment] 2017-02-06 02:20
@AlexejK Can a release be pushed out for the EAP? I tried to build from the head but was unsuccessful; my setup could have issues.
