### ISSUE TITLE
@CustomLog not supported

### ISSUE THREAD

**Issue by ajaijohn** [mplushnikov/lombok-intellij-plugin#696] opened 2019-10-29 10:07 UTC
### Short description
@CustomLog does not give the variable suggestion even though the after mvn compile it generates the code in class file(with log variable)

### Expected behavior
Was expecting the log variable suggested as when using @Slf4j 

### Version information

 * **IDEA Version:** 2019.2.3
 * **JDK Version:** OpenJDK 64 bit server VM by JetBrains (Runtime version 11.0.4+10-b304.69 X86_64)
 * **OS Type & Version:** Mac Mojave 10.14.6
 * **Lombok Plugin Version:** 0.27-2019.2
 * **Lombok Dependency Version:** 1.18.10

### Steps to reproduce
_What steps do we need to take to reproduce this issue?_

 1. install plugin and enable annotation processing
 2. add lombok to maven compiler plugin
 3. create a java file in source dir with @CustomLog annotation after creating the lombok.config file with lombok.log.custom.declaration

**Comment by LaP0573** [comment] 2019-10-30 07:46
This is a duplicate of #672

**Comment by mplushnikov** [comment] 2019-10-30 19:53
Support for @CustomLog will be avaliable in the next version of plugin (0.28)

**Closed by mplushnikov** 2019-10-30 19:53 UTC
