### ISSUE TITLE
Refactoring classes marked @Builder doesn't cascade changes

### ISSUE THREAD

**Issue by Bekreth** [mplushnikov/lombok-intellij-plugin#442] opened 2018-01-22 16:49 UTC
When you have a pho marked with an @Builder annotation, refactoring the fields in the object doesn't translate to refactoring the builder methods throughout the code.

Ideally, this should work the same way it does for getters/setters where refactoring the name of the field causes Intellij to also refactor the names of the associated methods.

**Comment by rijnb** [comment] 2018-02-23 12:31
I can confirm this bug - having the same problem here.

**Comment by mplushnikov** [comment] 2018-03-28 18:49
Closed as duplicate of #119

**Closed by mplushnikov** 2018-03-28 18:49 UTC
