### ISSUE TITLE
Component name collision: UpdateComponent class de.plushnikov.intellij.plugin.LombokPluginUpdateProjectComponent and class mobi.hsz.idea.gitignore.UpdateComponent

### ISSUE THREAD

**Issue by costalfy** [mplushnikov/lombok-intellij-plugin#347] opened 2017-01-24 09:32 UTC
Always i start IdeaIU 2017.1 EAP (build 171.2455.10) i have this error message :
`
Component name collision: UpdateComponent class de.plushnikov.intellij.plugin.LombokPluginUpdateProjectComponent and class mobi.hsz.idea.gitignore.UpdateComponent
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:432)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.access$300(ComponentManagerImpl.java:58)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:492)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:125)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:109)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:96)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:285)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:239)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.newProject(ProjectManagerImpl.java:171)
	at com.intellij.openapi.project.ex.ProjectManagerEx.createProject(ProjectManagerEx.java:71)
	at com.intellij.ide.util.projectWizard.ProjectBuilder.createProject(ProjectBuilder.java:81)
	at com.intellij.ide.impl.NewProjectUtil.a(NewProjectUtil.java:109)
	at com.intellij.ide.impl.NewProjectUtil.createFromWizard(NewProjectUtil.java:76)
	at com.intellij.ide.actions.ImportModuleAction.a(ImportModuleAction.java:95)
	at com.intellij.ide.actions.ImportModuleAction.a(ImportModuleAction.java:89)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:89)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:157)
	at com.intellij.ide.actions.ImportModuleAction.createFromWizard(ImportModuleAction.java:89)
	at com.intellij.openapi.vcs.checkout.NewProjectCheckoutListener.processCheckedOutDirectory(NewProjectCheckoutListener.java:50)
	at com.intellij.openapi.vcs.checkout.CompositeCheckoutListener.a(CompositeCheckoutListener.java:62)
	at com.intellij.openapi.vcs.checkout.CompositeCheckoutListener.directoryCheckedOut(CompositeCheckoutListener.java:53)
	at git4idea.checkout.GitCheckoutProvider$1.onSuccess(GitCheckoutProvider.java:103)
	at com.intellij.openapi.progress.impl.CoreProgressManager.finishTask(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.a(ProgressManagerImpl.java:161)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:408)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:397)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:818)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

**Comment by AlexejK** [comment] 2017-01-25 10:19
This is a duplicate of #337 which has been resolved in the head.

**Closed by AlexejK** 2017-01-25 10:19 UTC
Labels: duplicate
