### ISSUE TITLE
0.30-2020.1 not compatible with 2020.2

### ISSUE THREAD

**Issue by mercer** [mplushnikov/lombok-intellij-plugin#851] opened 2020-07-31 11:50 UTC
### Short description
After updating IDEA to latest, plugin no longer compatible. Latest available version installed.

### Expected behavior
Plugin should work. Plugin should be updated to latest.

### Version information

```
IntelliJ IDEA 2020.2 (Ultimate Edition)
Build #IU-202.6397.94, built on July 27, 2020
Subscription is active until September 3, 2020
Runtime version: 11.0.7+10-b944.20 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-7634-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Non-Bundled Plugins: com.intellij.ideolog, org.intellij.plugins.hcl, org.sonarlint.idea, com.intellij.plugin.adernov.powershell
Current Desktop: pop:GNOME
```

### Steps to reproduce

 1. install plugin 0.30-2020.1 with idea < IntelliJ IDEA 2020.2
 2. update idea to IntelliJ IDEA 2020.2

**Comment by valentinprotiuc** [comment] 2020-07-31 12:04
Duplicate of #840

**Comment by zwdgit** [comment] 2020-08-01 02:33
+1

**Comment by pood1e** [comment] 2020-08-01 14:12
+1

**Closed** 2020-08-10 07:34 UTC
Labels: duplicate
