### ISSUE TITLE
got a stackoverflow

### ISSUE THREAD

**Issue by kaHaleMaKai** [mplushnikov/lombok-intellij-plugin#258] opened 2016-07-14 10:30 UTC
Hej Michail,

I just got a stackoverflow from the lombok plugin. You can find it attached. Thank you for providing us with this great plugin. It works like a charm and java feels much more pleasant :-)

Have a great day! Best,
Lars
[lombok-stacktrace.txt](https://github.com/mplushnikov/lombok-intellij-plugin/files/363466/lombok-stacktrace.txt)

**Comment by kaHaleMaKai** [comment] 2016-07-14 10:34
Sorry, I forgot to mention:

idea 15.0.6, #ic-143.2370
JAVA 1.8.0_60-b27 amd64 hotspot

Description:	Ubuntu 14.04.3 LTS
Linux kauai 3.16.0-37-generic #51~14.04.1-Ubuntu SMP Wed May 6 15:23:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by AlexejK** [comment] 2016-07-14 10:34
What Lombok plugin and dependency version are you running? 
Can you provide a small sample project that reproduces this issue?

**Comment by kaHaleMaKai** [comment] 2016-07-14 10:43
I am using lombok 1.16.8 and lombok-intellij-plugin 0.11.15.
I have only experienced today when working on my project
https://github.com/kaHaleMaKai/opencsv. But the error didn't occur on
startup, but after having it open for a few hours. Unfortunately, I
cannot reproduce the bug.

**Comment by AlexejK** [comment] 2016-07-15 07:34
IDEA 15 is "quite" old at this point but I'm not sure if the latest patch build for it made changes. I ran a quick tests and all of them are working fine. Generall stackoverflow is caused inside of IDEA and not lombok plugin. We had this issue with 2016.2 EAP build where a guard code inside IDEA was broken and caused similar problems.

Unless you could reproduce this, I'm going to have to close this. To improve your Lombok + IDEA experience I could suggest you upgrade to later version of IntelliJ simply because 2016.2 introduced some new APIs for us that finally allow modifier visibility changes - therefore support for some new functions is implemented there.

**Closed by AlexejK** 2016-07-15 07:34 UTC
