### ISSUE TITLE
Overloading of Builder Method not Handled Correctly

### ISSUE THREAD

**Issue by mikeholler** [mplushnikov/lombok-intellij-plugin#163] opened 2015-12-09 19:39 UTC
I have this class,

![screenshot from 2015-12-09 13 33 09](https://cloud.githubusercontent.com/assets/1164112/11696350/6e24b6b2-9e79-11e5-8c88-e56868aa14fc.png)

I should be able to create a new builder instance without error here. In fact, delombok shows that I can (Builder is at the package level, so I should be able to access it in my static method).

```java
// Generated by delombok at Wed Dec 09 13:34:30 CST 2015
package com.physiq.sdk.model;

public final class LombokTest {
    private final String field;
    private final String otherField;

    /**
     * LombokTest Builder.
     *
     * @param field the field value
     *
     * @return a new builder instance with field set
     */
    public static Builder newBuilder(final String field) {
        return new Builder().field(field);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    LombokTest(final String field, final String otherField) {
        this.field = field;
        this.otherField = otherField;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public static class Builder {
        @java.lang.SuppressWarnings("all")
        @javax.annotation.Generated("lombok")
        private String field;
        @java.lang.SuppressWarnings("all")
        @javax.annotation.Generated("lombok")
        private String otherField;

        @java.lang.SuppressWarnings("all")
        @javax.annotation.Generated("lombok")
        Builder() {
        }

        @java.lang.SuppressWarnings("all")
        @javax.annotation.Generated("lombok")
        public Builder field(final String field) {
            this.field = field;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @javax.annotation.Generated("lombok")
        public Builder otherField(final String otherField) {
            this.otherField = otherField;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @javax.annotation.Generated("lombok")
        public LombokTest build() {
            return new LombokTest(field, otherField);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @javax.annotation.Generated("lombok")
        public java.lang.String toString() {
            return "LombokTest.Builder(field=" + this.field + ", otherField=" + this.otherField + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public String getField() {
        return this.field;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public String getOtherField() {
        return this.otherField;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof LombokTest)) return false;
        final LombokTest other = (LombokTest)o;
        final java.lang.Object this$field = this.getField();
        final java.lang.Object other$field = other.getField();
        if (this$field == null ? other$field != null : !this$field.equals(other$field)) return false;
        final java.lang.Object this$otherField = this.getOtherField();
        final java.lang.Object other$otherField = other.getOtherField();
        if (this$otherField == null ? other$otherField != null : !this$otherField.equals(other$otherField)) return false;
        return true;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $field = this.getField();
        result = result * PRIME + ($field == null ? 43 : $field.hashCode());
        final java.lang.Object $otherField = this.getOtherField();
        result = result * PRIME + ($otherField == null ? 43 : $otherField.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.lang.String toString() {
        return "LombokTest(field=" + this.getField() + ", otherField=" + this.getOtherField() + ")";
    }
}
```

Furthermore, when I try to *use* the builder I created, I see this:

![screenshot from 2015-12-09 13 36 17](https://cloud.githubusercontent.com/assets/1164112/11696435/d7584f54-9e79-11e5-8d26-e4fef83f8bda.png)

Notice how there are two "newBuilder" methods. In reality, does not generate `newBuilder()` in this case, but instead keeps only the `newBuilder(String)` method.

I should expect:
* There to be no error when calling `new Builder(...)` anywhere in LombokTest
* There to be no `newBuilder()` method displayed in the class structure when a custom `newBuilder` method is specified

**Comment by mplushnikov** [comment] 2016-01-12 21:03
Thank you for good description and example! 

We have two separate issues here:

The second one "multiple newBuilder() methods" will be fixed in the next plugin version.

The first one "error on new Builder()" is still under deeper investigation....

**Comment by mplushnikov** [comment] 2016-01-12 21:07
Duplicate of #145

**Comment by mplushnikov** [comment] 2016-01-31 14:35
Plugin 0.9.8 was released today. 
Problem with "multiple newBuilder() methods" should be fixed now.
Another one ("error on new Builder()") will be tracked by #145

**Closed by mplushnikov** 2016-01-31 14:35 UTC
Labels: bug, duplicate, enhancement

**Comment by mattiasoamz** [comment] 2016-02-15 19:21
Hi, I'm still having this problem and I'm on plugin 0.9.8.15. If I overload the builder method (regardless of whether it has been renamed using "builderMethodName", the no args version of the method disappears. Its gone from the Structure view and I can't call it.
