### ISSUE TITLE
@SuperBuilder caused red highlighting

### ISSUE THREAD

**Issue by borneq** [mplushnikov/lombok-intellij-plugin#632] opened 2019-05-17 14:13 UTC
### Short description
I have superclass and subclass, both with @SuperBuilder. Using .builder is highlighted in IDE but is fair compiled

### Expected behavior
No highlighting

### Version information

 * **IDEA Version:2019.1.1 Ultimate Edition, build #IU-191.6707.61, built on April 16 2019 
 * **JDK Version:JRE 1.8.0_202-release-1483-b44 Amd64
JVM OpenJDK 64-Bit Server VM by JetBrains s.r.o
 * **OS Type & Version: Linux Mint 19 Tara on VirtualBox on Windows 10 
 * **Lombok Plugin Version:v025-2019.1

### Steps to reproduce
 1. Create class 
@SuperBuilder
public class BlockBase {
 2. Create class
@SuperBuilder
public class Block extends BlockBase {
 3. call 
Block blck = Block.builder()

**Comment by jcputney** [comment] 2019-05-18 00:26
@SuperBuilder isn't supported yet. See #513.

**Comment by jcezarms** [comment] 2019-06-11 17:50
@mplushnikov are plans of #513 in the 0.26 milestone?

**Comment by nbeucler** [comment] 2019-07-11 13:48
@SuperBuilder was supposed to be addes to 0.25 version of plugin but 0.25 is out and @Superbuilder is still not supported :-(

**Comment by tsrikarrao** [comment] 2019-07-12 19:39
Could you please let me know when can we expect this to be released?

**Comment by jcputney** [comment] 2019-07-14 16:47
We're almost at a full year from when the initial issue was created. Is there anyway we can help? Any testing that can be done?

**Comment by AlexLeung** [comment] 2019-07-22 15:45
If you want it then write a PR for it. That's how OSS works.

**Comment by jcputney** [comment] 2019-07-22 16:20
Well, considering @mplushnikov has already said he is working on it, why would I duplicate effort?

**Comment by marc0olo** [comment] 2019-07-23 07:52
yes, would be nice to know about the state of #513 

I expected it to be released with version 0.25 :(

**Comment by AlexLeung** [comment] 2019-07-31 03:31
You might duplicate some effort, but on the plus side the feature will actually be finished. Your trade-off to make. It's never good idea to push all the feature requests for a large project onto one person, and expect them all to be finished. Not criticizing any one person in particular, it's just an unfortunate state of affairs I notice many indie open source projects are in.

**Comment by boonware** [comment] 2019-08-23 09:42
@mplushnikov Apologies for further spam on this issue, but I think the community would really appreciate a rough indication of when a fix for this issue (https://github.com/mplushnikov/lombok-intellij-plugin/issues/513) will be released, since you stated it was on your TODO list?

**Comment by mplushnikov** [comment] 2019-08-23 10:01
@boonware I'm very sorry! It is still on my TODO-List. 
But I didn't find enougth time to implement this functionality last months. 
It needs a lot of work and experiments with augmented generics types because of they very intensive using by lombok in behind. 

Anybody is free to implement it themself and send PR. But for me it will be done, when it's done :-)

**Comment by boonware** [comment] 2019-08-23 10:32
@mplushnikov Thanks for the update, that's reasonable. At least we know where we currently stand :)

**Comment by mplushnikov** [comment] 2019-08-25 13:25
Closed this as duplicate of #513

**Closed by mplushnikov** 2019-08-25 13:25 UTC
