### ISSUE TITLE
use jdk8  getter add annaotion show abnormality

### ISSUE THREAD

**Issue by huangmiao** [mplushnikov/lombok-intellij-plugin#501] opened 2018-07-09 08:42 UTC
### Short description
Intellij displays an error when annotating a getter method
### Expected behavior
Intellij displays an error when annotating a method, which is an unfriendly way

### Version information

 * **IDEA Version:**2018.1.5
 * **JDK Version:**  1.8.131
 * **OS Type & Version:**  windows10
 * **Lombok Plugin Version:**   0.18-2018.1
 * **Lombok Dependency Version:** 1.18.0

### Steps to reproduce

 1. create entity
 2. @Getter(onMethod_={@ApiModelProperty(name="门店名称")})
     private String storeName;

```

**Comment by mplushnikov** [comment] 2018-07-09 18:49
Duplicate of #382

**Closed by mplushnikov** 2018-07-09 18:49 UTC
