### ISSUE TITLE
poly expression evaluation during overload resolution

### ISSUE THREAD

**Issue by dodalovic** [mplushnikov/lombok-intellij-plugin#492] opened 2018-06-14 19:56 UTC
```
IntelliJ IDEA 2018.1.5 (Ultimate Edition)
Build #IU-181.5281.24, built on June 12, 2018
JRE: 1.8.0_152-release-1136-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.5
```

```
poly expression evaluation during overload resolution
java.lang.Throwable: poly expression evaluation during overload resolution
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl$TypeEvaluator.fun(PsiMethodCallExpressionImpl.java:168)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl$TypeEvaluator.fun(PsiMethodCallExpressionImpl.java:140)
	at com.intellij.psi.impl.source.resolve.JavaResolveCache.getType(JavaResolveCache.java:94)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.getType(PsiMethodCallExpressionImpl.java:40)
	at de.plushnikov.intellij.plugin.processor.ValProcessor$2.compute(ValProcessor.java:188)
	at de.plushnikov.intellij.plugin.processor.ValProcessor$2.compute(ValProcessor.java:185)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:67)
	at de.plushnikov.intellij.plugin.processor.ValProcessor.processLocalVariableInitializer(ValProcessor.java:185)
	at de.plushnikov.intellij.plugin.processor.ValProcessor.inferType(ValProcessor.java:142)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.inferType(LombokAugmentProvider.java:95)
	at com.intellij.psi.augment.PsiAugmentProvider.lambda$getInferredType$1(PsiAugmentProvider.java:102)
	at com.intellij.psi.augment.PsiAugmentProvider.forEach(PsiAugmentProvider.java:134)
	at com.intellij.psi.augment.PsiAugmentProvider.getInferredType(PsiAugmentProvider.java:101)
	at com.intellij.psi.impl.source.PsiTypeElementImpl.calculateType(PsiTypeElementImpl.java:69)
	at com.intellij.psi.impl.source.PsiTypeElementImpl.lambda$getType$0(PsiTypeElementImpl.java:65)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:140)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:87)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:139)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:126)
	at com.intellij.psi.impl.source.PsiTypeElementImpl.getType(PsiTypeElementImpl.java:65)
	at com.intellij.psi.impl.source.tree.JavaSharedImplUtil.getType(JavaSharedImplUtil.java:49)
	at com.intellij.psi.impl.source.tree.JavaSharedImplUtil.getType(JavaSharedImplUtil.java:45)
	at com.intellij.psi.impl.source.tree.java.PsiLocalVariableImpl.getType(PsiLocalVariableImpl.java:98)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$TypeEvaluator.fun(PsiReferenceExpressionImpl.java:394)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$TypeEvaluator.fun(PsiReferenceExpressionImpl.java:368)
	at com.intellij.psi.impl.source.resolve.JavaResolveCache.getType(JavaResolveCache.java:94)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.getType(PsiReferenceExpressionImpl.java:435)
	at com.intellij.psi.impl.source.resolve.graphInference.constraints.ExpressionCompatibilityConstraint.reduce(ExpressionCompatibilityConstraint.java:45)
	at com.intellij.psi.impl.source.resolve.graphInference.InferenceSession.reduceConstraints(InferenceSession.java:992)
	at com.intellij.psi.impl.source.resolve.graphInference.InferenceSession.repeatInferencePhases(InferenceSession.java:975)
	at com.intellij.psi.impl.source.resolve.graphInference.InferenceSession.processOneConstraint(InferenceSession.java:1443)
	at com.intellij.psi.impl.source.resolve.graphInference.InferenceSession.proceedWithAdditionalConstraints(InferenceSession.java:1413)
	at com.intellij.psi.impl.source.resolve.graphInference.InferenceSession.doInfer(InferenceSession.java:398)
	at com.intellij.psi.impl.source.resolve.graphInference.InferenceSession.performGuardedInference(InferenceSession.java:336)
	at com.intellij.psi.impl.source.resolve.graphInference.InferenceSession.infer(InferenceSession.java:326)
	at com.intellij.psi.impl.source.resolve.graphInference.InferenceSession.infer(InferenceSession.java:318)
	at com.intellij.psi.impl.source.resolve.graphInference.InferenceSessionContainer.infer(InferenceSessionContainer.java:128)
	at com.intellij.psi.impl.source.resolve.graphInference.PsiGraphInferenceHelper.inferTypeArguments(PsiGraphInferenceHelper.java:54)
	at com.intellij.psi.impl.source.resolve.PsiResolveHelperImpl.inferTypeArguments(PsiResolveHelperImpl.java:192)
	at com.intellij.psi.infos.MethodCandidateInfo.lambda$inferTypeArguments$3(MethodCandidateInfo.java:423)
	at com.intellij.psi.infos.MethodCandidateInfo.computeForOverloadedCandidate(MethodCandidateInfo.java:274)
	at com.intellij.psi.infos.MethodCandidateInfo.inferTypeArguments(MethodCandidateInfo.java:410)
	at com.intellij.psi.infos.MethodCandidateInfo.inferTypeArguments(MethodCandidateInfo.java:389)
	at com.intellij.psi.infos.MethodCandidateInfo.getSubstitutor(MethodCandidateInfo.java:316)
	at com.intellij.psi.infos.MethodCandidateInfo.getSubstitutor(MethodCandidateInfo.java:301)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.captureReturnType(PsiMethodCallExpressionImpl.java:223)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl$TypeEvaluator.getResultType(PsiMethodCallExpressionImpl.java:212)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl$TypeEvaluator.fun(PsiMethodCallExpressionImpl.java:171)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl$TypeEvaluator.fun(PsiMethodCallExpressionImpl.java:140)
	at com.intellij.psi.impl.source.resolve.JavaResolveCache.getType(JavaResolveCache.java:94)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.getType(PsiMethodCallExpressionImpl.java:40)
	at com.intellij.psi.scope.util.PsiScopesUtil.setupAndRunProcessor(PsiScopesUtil.java:317)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.resolveToMethod(PsiReferenceExpressionImpl.java:306)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.resolve(PsiReferenceExpressionImpl.java:284)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.access$000(PsiReferenceExpressionImpl.java:47)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolve(PsiReferenceExpressionImpl.java:189)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolve(PsiReferenceExpressionImpl.java:178)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:205)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:204)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:724)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:715)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.multiResolve(PsiReferenceExpressionImpl.java:352)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.advancedResolve(PsiReferenceExpressionImpl.java:524)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.resolveMethodGenerics(PsiMethodCallExpressionImpl.java:51)
	at com.intellij.codeInsight.hints.JavaInlayHintsProvider.hints(JavaHintUtils.kt:42)
	at com.intellij.codeInsight.hints.JavaInlayParameterHintsProvider.getParameterHints(JavaInlayParameterHintsProvider.kt:30)
	at com.intellij.codeInsight.hints.ParameterHintsPass.process(ParameterHintsPass.java:84)
	at com.intellij.codeInsight.hints.ParameterHintsPass.lambda$doCollectInformation$0(ParameterHintsPass.java:76)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.intellij.codeInsight.hints.ParameterHintsPass.doCollectInformation(ParameterHintsPass.java:76)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:437)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:430)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:429)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:403)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:170)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by dmitriysemyonov** [comment] 2018-06-15 14:34
Same error as above when using "val".

IntelliJ IDEA 2017.3.5 (Community Edition)
Build #IC-173.4674.33, built on March 5, 2018
JRE: 1.8.0_152-release-1024-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**Comment by bpl** [comment] 2018-06-19 06:51
FYI, I just posted a testcase to https://github.com/mplushnikov/lombok-intellij-plugin/issues/364 which I believe is the same problem.

**Comment by mplushnikov** [comment] 2018-06-24 20:17
Thank you @bpl , you are right, it's duplicate of #364

**Closed by mplushnikov** 2018-06-24 20:17 UTC
