### ISSUE TITLE
android studio 提示错误，但是能运行

### ISSUE THREAD

**Issue by CloudJoe** [mplushnikov/lombok-intellij-plugin#708] opened 2019-11-28 10:31 UTC
Lombok Requires Annotation Processing
			Annotation processing seems to be disabled for the project "XXXX". But lombok is on classpath.
			For the lombok plugin to function correctly, please enable it under
			"Settings > Build > Compiler > Annotation Processors"

**Comment by robcanini** [comment] 2019-12-01 10:41
Same problem here.
I'm using Android Studio 4.0 Canary 4 and i was not able to find annotation processors settings.
How can we enable that?

**Comment by robcanini** [comment] 2019-12-01 11:03
The working solution for me was to Reorder my annotation processor declarations moving lombok up above the room compiler.

**Comment by mplushnikov** [comment] 2019-12-01 18:16
Close this as duplicate of #264

**Closed by mplushnikov** 2019-12-01 18:16 UTC
