### ISSUE TITLE
Intellij does not recognize fields on constructor creation if annotated with @Getter and @Setter

### ISSUE THREAD

**Issue by cchet** [mplushnikov/lombok-intellij-plugin#227] opened 2016-04-22 15:45 UTC
If a class defines Properties in the following way:

```
@Getter
@Setter
public Integer id;
```

then Intellij IDE does not recognize the filed on 'generate' -> 'constructors' and will not provide selection for the fields with this signature. If all properties have been defined in this way and an empty contructor is already defined within the class, then Intellij will tell you that already all constructors have been created for this class. Therefore we need to write our contructors on our own.

**Comment by orange-buffalo** [comment] 2016-06-28 07:43
It looks like this is a bug which was already fixed in #149 (although it is reproducible again).

**Comment by mplushnikov** [comment] 2017-01-14 21:59
Hello @orange-buffalo, @cchet 
can you please check new version 0.14 of the plugin? I thnik this issue was fixed by changes for #320 too.

**Comment by orange-buffalo** [comment] 2017-02-01 11:47
Hi All,
I have checked this on `0.14.16` and the problem is not reproducible - fields are suggested for constructor parameters if they are annotated.

**Comment by mplushnikov** [comment] 2018-10-03 19:45
Thank you @orange-buffalo !

**Closed by mplushnikov** 2018-10-03 19:45 UTC
Labels: waiting-for-feedback
