### ISSUE TITLE
Add support for @With tag 

### ISSUE THREAD

**Issue by chriswwalz** [mplushnikov/lombok-intellij-plugin#677] opened 2019-10-02 18:28 UTC
### Short description

@With annotation shows compile error. 

### Expected behavior

@With annotation should compile. The plugin seems to only support deprecated @Wither  

Intellij 2019.2.3

**Comment by mplushnikov** [comment] 2019-10-02 18:30
Duplicate of #673. New plugin version will be probably released this week.

**Closed by mplushnikov** 2019-10-02 18:30 UTC
