### ISSUE TITLE
lombok.config doesn't works

### ISSUE THREAD

**Issue by pedegie** [mplushnikov/lombok-intellij-plugin#456] opened 2018-02-18 16:01 UTC
### Short description
lombok.fieldDefaults.defaultPrivate = true
lombok.fieldDefaults.defaultFinal = true
These properties doesn't affects my classes. If i put @FieldDefaults directly above class then it works.
I put lombok.config file in root directory

### Version information

 * **IDEA Version:** Intellij Idea Ultimate EAP 2018.1
 * **JDK Version:** 1.8
 * **OS Type & Version:** Windows
 * **Lombok Plugin Version:** 0.15.17.2
 * **Lombok Dependency Version:** 1.16.20

### Steps to reproduce
Just put lombok.config with properties described in Short description then 

 1. Create class in lombok.config scope
@RequiredArgsConstructor
public class ProductSearchParams {
    Set<QueryParameter> parameters;
}
 2. It's possible to invoke ProductSearchParams p = new ProductSearchParams(); // no required argument

3. Put  @FieldDefaults(makeFinal=true, level=AccessLevel.PRIVATE) above class

4. NOT possible to call ProductSearchParams constructor without argument
 

### Sample project
Please provide a sample project that exhibits the problem.
You should also include `.idea` folder so we can inspect the settings.

 - [ ] Sample project provided
 - [x ] I am able to reproduce this error on the sample project by following the steps described above

**Comment by krzyk** [comment] 2018-03-25 14:15
lombok plugin is not compatible with IDEA 2018.1 (see #449)

**Comment by mplushnikov** [comment] 2018-07-10 18:36
duplicate of #353

**Closed by mplushnikov** 2018-07-10 18:36 UTC
Labels: enhancement

**Comment by FeanorsCurse** [comment] 2018-07-24 11:09
I still have the issue of this not working:

```
config.stopBubbling = true
lombok.extern.findbugs.addSuppressFBWarnings=true
```

I placed lombok.config in '/', '/src/main/java', and in '/src/main/java/my/package'
