### ISSUE TITLE
No usages found for fields if using Builder annotation

### ISSUE THREAD

**Issue by klimmik** [mplushnikov/lombok-intellij-plugin#362] opened 2017-02-28 16:42 UTC
![20170228-lombok-builder-no-usages](https://cloud.githubusercontent.com/assets/13970931/23414697/f0ca0fa2-fded-11e6-8763-ee9f2d4702e8.png)

**Comment by LuiVampa** [comment] 2017-03-01 07:17
I'm too!

**Comment by CoolHacker999** [comment] 2017-03-13 12:15
I'd like this to be fixed as soon as possible!

**Comment by mplushnikov** [comment] 2017-10-03 11:38
duplicate of #144

**Closed by mplushnikov** 2017-10-03 11:38 UTC
Labels: enhancement, Search usages
