### ISSUE TITLE
@EqualsAndHashCode unnecessary warning

### ISSUE THREAD

**Issue by fredo994** [mplushnikov/lombok-intellij-plugin#209] opened 2016-04-10 20:32 UTC
@EqualsAndHashCode(of = {"val"}) gives a warning:
Generating equals/hashCode implementation but without a call to superclass, even though this class does not extend java.lang.Object.If this is intentional, add '(callSuper=false)' to your type.

And callSuper = false is default value.

![screenshot from 2016-04-10 22 29 15](https://cloud.githubusercontent.com/assets/7530821/14412886/b6e62f0e-ff6b-11e5-8b4d-416a4efa66ab.png)
![screenshot from 2016-04-10 22 30 04](https://cloud.githubusercontent.com/assets/7530821/14412890/c8c38bc2-ff6b-11e5-9dfb-44fbbbefc726.png)

**Comment by AlexejK** [comment] 2016-04-10 20:41
What version of the plugin are you using? Please also provide version of intelliJ you are on.
I believe this has been fixed in #184 which was part of 0.10 release of this plugin

**Comment by fredo994** [comment] 2016-04-10 21:05
Lombok Plugin Version: 0.11.16 
IntelliJ IDEA 2016.1.1
Build #IU-145.597, built on March 29, 2016
JRE: 1.8.0_76-release-b18 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by AlexejK** [comment] 2016-04-10 21:16
Interesting. This is very similar to my setup i'm testing on.
Could you please provide a sample code or a project to reproduce this?

**Comment by fredo994** [comment] 2016-04-10 21:19
![screenshot from 2016-04-10 23 18 58](https://cloud.githubusercontent.com/assets/7530821/14413191/a1cefa4a-ff72-11e5-8a7e-51d25e113041.png)

**Comment by AlexejK** [comment] 2016-04-11 07:47
The warning is valid, as per [https://projectlombok.org/features/EqualsAndHashCode.html](lombok documentation).

> Not setting callSuper to true when you extend another class generates a warning, because unless the superclass has no (equality-important) fields, lombok cannot generate an implementation for you that takes into account the fields declared by your superclasses. You'll need to write your own implementations, or rely on the callSuper chaining facility.

**Comment by eepstein** [comment] 2016-04-22 21:01
There's a related issue - not sure whether I should open a separate thread for this:

@Data // Warning issued even though this class implements its own equals() and hashCode() methods.
public class Foo extends Bar {

...

    @Override
    public boolean equals(Object o) {
        return ...;
    }

    @Override
    public int hashCode() {
        return ...;
    }
}

The plugin warns that super is not being called for equals and hashCode... but that check seems to overlook that this class isn't using that part of the @Data feature.

**Closed** 2017-01-11 19:48 UTC
Labels: enhancement

**Comment by navneetkarnani** [comment] 2017-04-14 19:18
I'm still seeing this error on 1.16.16

**Comment by kaliatech** [comment] 2017-10-05 15:06
As an aside for others that might stumble upon this... I was also seeing this and thinking it was a bug. Seemingly, setting `callSuper=false` _or_ `callSuper=true` still always resulted in the warning. However, I eventually found that it was because intellij's automatic import was pulling in the `groovy.transform.EqualsAndHashCode` annotation instead of the correct `lombok.EqualsAndHashCode`. Be sure to check imports if unable to explain otherwise.
