### ISSUE TITLE
@With annotation not supported for Nullable fields or Optionals

### ISSUE THREAD

**Issue by frtelg** [mplushnikov/lombok-intellij-plugin#678] opened 2019-10-03 12:30 UTC
### Short description
I have recently upgraded my Lombok to version 1.18.10, in which the @Wither annotation is no longer experimental. So I changed all the uses of @Wither to @With, since this is the new name of this annotation. 

Now the 'with' methods of Nullable fields and Optionals turn red, indicating that the method does not exist. The code however compiles and I am able to run my tests without errors.

### Expected behavior
with-method is available for the nullable and optional fields as well.

### Version information

 * **IDEA Version:** 2019.2.3
 * **JDK Version:** openjdk 11.0.2 2019-01-15
 * **OS Type & Version:** MacOS X 10.14.6 Mojave
 * **Lombok Plugin Version:** 0.26.2-2019.2
 * **Lombok Dependency Version:** 1.18.10

### Steps to reproduce
Apply @With annotation to a Nullable field or an Optional

**Comment by mplushnikov** [comment] 2019-10-03 12:38
Duplicate of #673. New plugin version will be probably released this week.

**Closed by mplushnikov** 2019-10-03 12:38 UTC
