### ISSUE TITLE
"Find usages" of a field doesn't find usage in Builders

### ISSUE THREAD

**Issue by jnazander** [mplushnikov/lombok-intellij-plugin#451] opened 2018-02-09 08:22 UTC
### Short description
When clicking 'Find Usages' or ctrl+clicking on a field of a class that has a Lombok builder added to it using `@Builder`, those instances where this field is set via that builder are not included in the usages.

This creates a problem of refactoring, as developers need to know _all_ usages of a particular variable, including where it's being set via builders.

### Expected behavior
Upon clicking 'Find Usages' or ctrl+clicking on a field, it should include all instances where this field is set via the builder of that class

### Version information

 * **IDEA Version:**
2017.3.2 Ultimate
Build #IU-173.4127.27
 * **JDK Version:**
JRE: 1.8.0_152-release-1024-b8 amd64
 * **OS Type & Version:** Windows 10
 * **Lombok Plugin Version:**
0.15.17.2
 * **Lombok Dependency Version:** lombok-1.16.10.jar

### Steps to reproduce

 1. Create a simple class with one field and a Lombok builder:
![image](https://user-images.githubusercontent.com/4726607/36017914-594aeaf2-0d82-11e8-80d4-52eadf589397.png)

2. Build this class and set the field to some value:
![image](https://user-images.githubusercontent.com/4726607/36017941-75e99faa-0d82-11e8-8b77-e48682ea6324.png)

3. Try to find usages of the field that was set in the builder:
![image](https://user-images.githubusercontent.com/4726607/36017957-91d25856-0d82-11e8-9609-9a2e149bb4d2.png)

**Comment by mplushnikov** [comment] 2018-07-15 12:14
Closed as duplicate of #144

**Closed by mplushnikov** 2018-07-15 12:14 UTC
Labels: Search usages
