### ISSUE TITLE
Does not support @Builder.Default in Lombok 1.16.16

### ISSUE THREAD

**Issue by namhnguyen** [mplushnikov/lombok-intellij-plugin#375] opened 2017-04-05 06:28 UTC
Field(s) annotated with @Builder.Default won't show up in Code Completion dropdown.

**Comment by kaiwaldron** [comment] 2017-04-06 20:43
+1

**Comment by kssd** [comment] 2017-04-11 07:38
+1

**Comment by maciejsobala** [comment] 2017-04-19 09:08
+1

**Comment by andrewmash** [comment] 2017-04-20 17:07
+1. Also, getters and setters created this way cannot be resolved.

**Comment by tanadeau** [comment] 2017-04-21 13:35
+1. We would love to use this feature.

**Comment by Sagar1704** [comment] 2017-04-26 19:04
+1. The tests run successfully. But it is bit annoying to look at the red lines in Intellij. And it also masks any other errors that may be present after the line where it cannot recognize the field.

**Comment by agirardeaudale** [comment] 2017-04-27 20:18
+1

**Comment by clayreimann** [comment] 2017-04-29 16:39
If you can point to where this change might need to happen, I'd be willing to do the work but looking at the code I can't make heads or tails of why this doesn't work out of the box

**Comment by imagest** [comment] 2017-05-23 20:20
+1

**Comment by tpweber** [comment] 2017-05-30 20:50
+1

**Comment by BlackRabbitCoder** [comment] 2017-06-12 18:05
+1

**Comment by awalland** [comment] 2017-06-21 13:10
+1

**Comment by altakacs** [comment] 2017-06-22 12:08
+1

**Comment by chrgue** [comment] 2017-06-26 08:42
+1

**Comment by vlopez** [comment] 2017-06-29 22:23
+1

**Comment by jmax01** [comment] 2017-07-06 19:31
+1

**Comment by aayushgupta** [comment] 2017-07-12 21:44
+1

**Comment by notflorian** [comment] 2017-07-13 14:40
+1

**Comment by Skiggz** [comment] 2017-07-14 22:05
+1

**Comment by AlexejK** [comment] 2017-07-17 08:50
Hi all, please note that spamming +1 does not help anyone. If you want to be a watcher either just select "Watch" or use the reaction on the original issue to show your support / request for this issue, like many others did.

As this is a voluntary project - it may take a looong time until we find time to look into issues, unless we face them ourselves and are blocked by it in our day-to-day work.

**Comment by clayreimann** [comment] 2017-07-17 18:00
@AlexejK if you would be willing to provide some guidance on how the plugin works I'd be more than happy to try and tackle this issue. I took a look at the code but can't make heads or tails how this plugin does its work.

**Comment by MattSainz** [comment] 2017-07-17 21:52
+1

**Comment by jvelliott** [comment] 2017-08-09 20:36
Does this issue only occur when attempting to use the annotation specifically as ```@Builder.Default```?

It seems to work ok for me when I import like 
```import lombok.Builder.Default;```

![autocomplete and no error](https://user-images.githubusercontent.com/4493308/29142721-a8209d86-7d07-11e7-855a-a7a50c06031d.png)

**Comment by patrickianwilson** [comment] 2017-08-10 22:35
It appears that this only happens (for me) when the property being annotated is explicitly marked as final.

```java

/* this works */
@Builder.Default() String foo = ""

/* this builder method won't be visible in the dropdown */
@Builder.Default() final String foo = ""

```

**Comment by saidaspen** [comment] 2017-08-20 18:56
+1

**Comment by winder** [comment] 2017-08-28 15:56
One way to reproduce this issue using Lombok `1.16.18` and intellij `2017.2`.

Start with this with everything imported:
```java
@Value
@Builder
public class LombokTest {
  @NonNull
  String value;
}
```

Add your builder default value:
```java
  @Builder.Default
  String value = "foo";
```

The builder setter for `value` isn't created (the `value(String)` method actually dissapears from the builder as soon as `= "foo";` is added):
<img width="606" alt="screen shot 2017-08-28 at 11 52 31 am" src="https://user-images.githubusercontent.com/125509/29781540-81e7e9dc-8be7-11e7-8bb6-d5eed0d6b843.png">

If I comment out `@Value` the builder `value(String)` method appears immediately:
<img width="621" alt="screen shot 2017-08-28 at 11 54 07 am" src="https://user-images.githubusercontent.com/125509/29781592-b1000b46-8be7-11e7-9072-a04fa469c9a9.png">

Finally, uncommenting `@Value` leaves everything working as expected.

**Comment by sith** [comment] 2017-08-28 20:48
Are there any plans to fix it?

**Comment by AlexejK** [comment] 2017-08-29 08:26
Most likely yes, when we have time to look into it.
Feel free to create a PR if you are in a hurry :)

**Comment by Nicolas-GUILLAUME** [comment] 2018-02-02 19:14
Just going to +1 this :)

**Comment by Jessevanbekkum** [comment] 2018-02-10 12:10
Oops, did not test it with older versions of Intellij. I'll commit a fix

**Comment by Jessevanbekkum** [comment] 2018-02-12 09:18
Fixed. All tests pass now

**Comment by sarxos** [comment] 2018-03-21 08:51
When can we expect this fix to be released? This problem is really annoying. The only w/a right now is not to use `final` together with `@Builder.Default`, but dropping immutability where it's required is fundamentally a bad idea.

**Comment by bmdahmen** [comment] 2018-03-23 01:56
+1
This is the first time I will have to download Eclipse in over 2 years because this is unsupported in a package I am working with.

**Closed** 2018-03-25 19:24 UTC
Labels: enhancement
