### ISSUE TITLE
@Slf4j with IntelliJ

### ISSUE THREAD

**Issue by PSeitz** [mplushnikov/lombok-intellij-plugin#423] opened 2017-10-25 11:44 UTC
I have the same issue as #292  
I think it occurs when switching between different Log annotations.

It works again when I restart the IDE

IntelliJ Version is 2017.2.5
Lombok Plugin Version is 0.15.17.2

**Comment by mplushnikov** [comment] 2018-01-13 16:37
Looks like duplicate of #210

**Closed by mplushnikov** 2018-01-13 16:37 UTC
Labels: duplicate
