### ISSUE TITLE
@Builder - Builder class can't be found without a static import

### ISSUE THREAD

**Issue by naddeoa** [mplushnikov/lombok-intellij-plugin#116] opened 2015-06-17 21:37 UTC
I'm on IntelliJ CE and I'm seeing a lombok plugin bug. If I have this class

```java
@RequiredArgsConstructor(access = AccessLevel.PROTECTED)
@Builder
public class Context {
    private final String var;
   /* more vars */
}
```

I get an error when I try to use it from another class

```java
import com.package.Context.ContextBuilder; // can't find class

public class AnotherClass {
    
    public void method(){
        ContextBuilder = Context.builder(); // builder method is found
    }
}
```

However, if I change the import to a static import, it works just fine:

```java
import static com.package.Context.ContextBuilder;
```

I'm switching from Eclipse and there was no issue using the normal imports there. Also, I'm not sure if it makes a difference but in the Structure View, the generated builder class has a dark blue class icon next to it, while other classes and static inner classes are light blue. I can't find that dark blue icon on the IntelliJ documentation either.

![dark_blue_class](https://cloud.githubusercontent.com/assets/1233709/8219349/3f879f2c-14fe-11e5-8f30-ec8a84bb1cb6.png)

**Comment by mplushnikov** [comment] 2015-06-20 09:55
This looks like duplicate of issue #48 and should be fixed in the next release 0.9.5.

**Closed** 2015-06-30 21:28 UTC
Labels: bug, duplicate

**Comment by mplushnikov** [comment] 2015-06-30 21:37
New plugin version 0.9.5 is available now!

**Comment by naddeoa** [comment] 2015-06-30 22:49
I just confirmed that the builder doesn't cause an error anymore, but I still can't click and go to its definition. Should I reopen?

**Comment by mplushnikov** [comment] 2015-07-01 06:25
Thank you! Please open new issue for "GoTo" functionality.

**Comment by davboecki** [comment] 2015-07-15 15:05
This still doesn't work if the Builder annotation is only present on the constructor and not on the class file. So: 
```
@RequiredArgsConstructor(access = AccessLevel.PROTECTED)
@Builder
public class Context {
    private final String var;
   /* more vars */
}
```
works but 
```
public class Context {
    @Builder
    public Context(String var) {
        this.var = var;
    }
    private final String var;
   /* more vars */
}
```
won't. The import still throws an error here.

**Comment by mplushnikov** [comment] 2015-07-15 17:34
Please open new issue for it.
