### ISSUE TITLE
Getting "Cannot resolve symbol <builder class>" at import statement

### ISSUE THREAD

**Issue by schmas** [mplushnikov/lombok-intellij-plugin#87] opened 2015-03-17 14:58 UTC
I'm using IntelliJ 14.0.3 and getting an error when trying to import a Builder class. An the type is not recognised on code. I thought that issue #83, would resolve, but I compiled the 0.9.2 milestone to test it, but it doesn't work at import statement. I can resolve by declaring all builder type declaration when using Class.Builder, and not importing.

For example:
That give an error.
```
import com.TestClass.TestClassBuilder;
-----
final TestClassBuilder builder = TestClass.builder();
final TestClass obj = builder.build();
```

And that works.
```
final TestClass.TestClassBuilder builder = TestClass.builder();
final TestClass obj = builder.build();
```

**Comment by mplushnikov** [comment] 2015-03-17 16:30
I think it is duplicate of #48

**Closed** 2015-04-06 10:50 UTC
Labels: duplicate
