### ISSUE TITLE
@Delegate: idea doesn't know that geter is used by @delegate

### ISSUE THREAD

**Issue by fedotxxl** [mplushnikov/lombok-intellij-plugin#104] opened 2015-04-25 15:09 UTC
Suppose I've got class `A` with getter `getData`. Class `B` delegates some calls to `A`. Some method calls `(new B()).getData()`. If I open `A` and try to find usages of `getData` (`alt`+`f7`) IDEA will not find anything + `getData` will be grey (which means it's not used)

I think it makes usage of `@Delegate` pretty dangerous (in case of refactoring). Can you fix it?

**Comment by mplushnikov** [comment] 2015-04-26 09:36
This is duplicate of #76 .

**Closed by mplushnikov** 2015-04-26 09:36 UTC
Labels: duplicate
