### ISSUE TITLE
com.intellij.util.IncorrectOperationException: Incorrect annotation '@org.spark-project.guava.annotations.GwtCompatible'

### ISSUE THREAD

**Issue by jnaous** [mplushnikov/lombok-intellij-plugin#150] opened 2015-10-27 15:21 UTC
This pops up once in a while, not sure why. On Idea 14.1.4.
```
Bad annotation in repository!: Incorrect annotation '@org.spark-project.guava.annotations.GwtCompatible'
com.intellij.util.IncorrectOperationException: Incorrect annotation '@org.spark-project.guava.annotations.GwtCompatible'
	at com.intellij.psi.impl.PsiJavaParserFacadeImpl.createAnnotationFromText(PsiJavaParserFacadeImpl.java:171)
	at com.intellij.psi.impl.PsiElementFactoryImpl.createAnnotationFromText(PsiElementFactoryImpl.java:652)
	at com.intellij.psi.impl.java.stubs.impl.PsiAnnotationStubImpl.getPsiElement(PsiAnnotationStubImpl.java:68)
	at com.intellij.psi.impl.compiled.ClsAnnotationImpl$1.compute(ClsAnnotationImpl.java:47)
	at com.intellij.psi.impl.compiled.ClsAnnotationImpl$1.compute(ClsAnnotationImpl.java:43)
	at com.intellij.openapi.util.AtomicNotNullLazyValue.getValue(AtomicNotNullLazyValue.java:40)
	at com.intellij.psi.impl.compiled.ClsAnnotationImpl.getNameReferenceElement(ClsAnnotationImpl.java:105)
	at de.plushnikov.intellij.plugin.util.PsiAnnotationUtil.getSimpleNameOf(PsiAnnotationUtil.java:105)
	at de.plushnikov.intellij.plugin.util.PsiAnnotationUtil.checkAnnotationsSimpleNameExistsIn(PsiAnnotationUtil.java:210)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.verifyLombokAnnotationPresent(LombokAugmentProvider.java:142)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.checkLombokPresent(LombokAugmentProvider.java:99)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.getAugments(LombokAugmentProvider.java:89)
	at com.intellij.psi.augment.PsiAugmentProvider.collectAugments(PsiAugmentProvider.java:44)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.b(ClassInnerStuffCache.java:176)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.access$300(ClassInnerStuffCache.java:38)
	at com.intellij.psi.impl.source.ClassInnerStuffCache$3.compute(ClassInnerStuffCache.java:75)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:131)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:200)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:83)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:127)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.getMethods(ClassInnerStuffCache.java:71)
	at com.intellij.psi.impl.compiled.ClsClassImpl.getMethods(ClsClassImpl.java:171)
	at com.intellij.psi.impl.PsiSuperMethodImplUtil.a(PsiSuperMethodImplUtil.java:164)
	at com.intellij.psi.impl.PsiSuperMethodImplUtil.access$000(PsiSuperMethodImplUtil.java:42)
	at com.intellij.psi.impl.PsiSuperMethodImplUtil$2$1.create(PsiSuperMethodImplUtil.java:60)
	at com.intellij.psi.impl.PsiSuperMethodImplUtil$2$1.create(PsiSuperMethodImplUtil.java:56)
	at com.intellij.util.containers.FactoryMap.get(FactoryMap.java:56)
	at com.intellij.psi.impl.PsiSuperMethodImplUtil$4.compute(PsiSuperMethodImplUtil.java:392)
	at com.intellij.psi.impl.PsiSuperMethodImplUtil$4.compute(PsiSuperMethodImplUtil.java:386)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.java:53)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:200)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:43)
	at com.intellij.psi.util.CachedValuesManager.getParameterizedCachedValue(CachedValuesManager.java:96)
	at com.intellij.psi.impl.PsiSuperMethodImplUtil.getHierarchicalMethodSignature(PsiSuperMethodImplUtil.java:380)
	at com.intellij.psi.impl.compiled.ClsMethodImpl.getHierarchicalMethodSignature(ClsMethodImpl.java:125)
	at com.intellij.psi.impl.search.MethodSuperSearcher$1.compute(MethodSuperSearcher.java:45)
	at com.intellij.psi.impl.search.MethodSuperSearcher$1.compute(MethodSuperSearcher.java:42)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:884)
	at com.intellij.psi.impl.search.MethodSuperSearcher.execute(MethodSuperSearcher.java:42)
	at com.intellij.psi.impl.search.MethodSuperSearcher.execute(MethodSuperSearcher.java:35)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:43)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:75)
	at com.intellij.util.UniqueResultsQuery.process(UniqueResultsQuery.java:66)
	at com.intellij.util.UniqueResultsQuery.forEach(UniqueResultsQuery.java:56)
	at com.intellij.util.UniqueResultsQuery.findAll(UniqueResultsQuery.java:78)
	at com.intellij.psi.impl.PsiSuperMethodImplUtil.a(PsiSuperMethodImplUtil.java:105)
	at com.intellij.psi.impl.PsiSuperMethodImplUtil.a(PsiSuperMethodImplUtil.java:89)
	at com.intellij.psi.impl.PsiSuperMethodImplUtil.findSuperMethods(PsiSuperMethodImplUtil.java:83)
	at com.intellij.psi.impl.PsiSuperMethodImplUtil.findSuperMethods(PsiSuperMethodImplUtil.java:71)
	at com.intellij.psi.impl.compiled.ClsMethodImpl.findSuperMethods(ClsMethodImpl.java:90)
	at com.intellij.codeInsight.ExpectedTypesProvider$MyParentVisitor.a(ExpectedTypesProvider.java:1237)
	at com.intellij.codeInsight.ExpectedTypesProvider$MyParentVisitor.visitReferenceExpression(ExpectedTypesProvider.java:301)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.accept(PsiReferenceExpressionImpl.java:676)
	at com.intellij.codeInsight.ExpectedTypesProvider$MyParentVisitor.visitMethodCallExpression(ExpectedTypesProvider.java:324)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.accept(PsiMethodCallExpressionImpl.java:139)
	at com.intellij.codeInsight.ExpectedTypesProvider.getExpectedTypes(ExpectedTypesProvider.java:149)
	at com.intellij.codeInsight.ExpectedTypesProvider.getExpectedTypes(ExpectedTypesProvider.java:118)
	at com.intellij.codeInsight.ExpectedTypesProvider.getExpectedTypes(ExpectedTypesProvider.java:113)
	at com.intellij.codeInsight.daemon.impl.quickfix.CreateFromUsageUtils.a(CreateFromUsageUtils.java:586)
	at com.intellij.codeInsight.daemon.impl.quickfix.CreateFromUsageUtils.guessMatchingVariables(CreateFromUsageUtils.java:526)
	at com.intellij.codeInsight.daemon.impl.quickfix.AddMethodQualifierFix.b(AddMethodQualifierFix.java:90)
	at com.intellij.codeInsight.daemon.impl.quickfix.AddMethodQualifierFix.a(AddMethodQualifierFix.java:77)
	at com.intellij.codeInsight.daemon.impl.quickfix.AddMethodQualifierFix.isAvailable(AddMethodQualifierFix.java:72)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.a(ShowIntentionsPass.java:131)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.access$000(ShowIntentionsPass.java:70)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass$1.process(ShowIntentionsPass.java:90)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass$1.process(ShowIntentionsPass.java:87)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl$5.process(DaemonCodeAnalyzerImpl.java:580)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl$5.process(DaemonCodeAnalyzerImpl.java:574)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerEx$1.process(DaemonCodeAnalyzerEx.java:59)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerEx$1.process(DaemonCodeAnalyzerEx.java:53)
	at com.intellij.openapi.editor.impl.MarkupModelImpl.processRangeHighlightersOverlappingWith(MarkupModelImpl.java:265)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerEx.processHighlights(DaemonCodeAnalyzerEx.java:53)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.processHighlightsNearOffset(DaemonCodeAnalyzerImpl.java:574)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getAvailableActions(ShowIntentionsPass.java:87)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:273)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.a(ShowIntentionsPass.java:212)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:188)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:189)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
```

**Comment by mplushnikov** [comment] 2016-03-26 18:10
I will close it at the moment, because I cannot reproduce it and it look like an one time thing.

**Closed by mplushnikov** 2016-03-26 18:10 UTC
