### ISSUE TITLE
Short name 'Convert2Diamond' is not unique

### ISSUE THREAD

**Issue by en-oro-cielito** [mplushnikov/lombok-intellij-plugin#429] opened 2017-11-23 09:20 UTC
### Short description
IDE Internal Error.

### Version information

 * **IDEA Version:** 
IntelliJ IDEA 2017.3 (Ultimate Edition)
Build #IU-173.3727.78, built on November 21, 2017

 * **JDK Version:** 
1.8.0_152-release-1024-b6 amd64

 * **OS Type & Version:** 
Windows 7 6.1

 * **Lombok Plugin Version:** 
0.14.16

 * **Lombok Dependency Version:** 
1.16.18

### Stacktrace
If you are experiencing an issue and IntelliJ throws an error please provide the stacktrace.

```

Short name 'Convert2Diamond' is not unique
class 'de.plushnikov.intellij.plugin.inspection.LombokExplicitTypeCanBeDiamondInspection' in PluginDescriptor[name='Lombok Plugin', classpath='~\.IntelliJIdea2017.3\config\plugins\lombok-plugin']
and
class'com.intellij.codeInspection.ExplicitTypeCanBeDiamondInspection' in PluginDescriptor[name='IDEA CORE', classpath='~\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\173.3727.78\lib\resources.jar']
conflict [Plugin: Lombook Plugin]
com.intellij.diagnostic.PluginException: Short name 'Convert2Diamond' is not unique
class 'de.plushnikov.intellij.plugin.inspection.LombokExplicitTypeCanBeDiamondInspection' in PluginDescriptor[name='Lombok Plugin', classpath='~\.IntelliJIdea2017.3\config\plugins\lombok-plugin']
and
class'com.intellij.codeInspection.ExplicitTypeCanBeDiamondInspection' in PluginDescriptor[name='IDEA CORE', classpath='~\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\173.3727.78\lib\resources.jar']
conflict [Plugin: Lombook Plugin]
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.a(InspectionToolRegistrar.java:86)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.a(InspectionToolRegistrar.java:60)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.createTools(InspectionToolRegistrar.java:127)
	at com.intellij.codeInspection.ex.InspectionSearchableOptionContributor.processOptions(InspectionSearchableOptionContributor.java:34)
	at com.intellij.ide.ui.search.SearchableOptionPreloader.preload(SearchableOptionPreloader.java:49)
	at com.intellij.openapi.application.Preloader.a(Preloader.java:74)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:534)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:479)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.Preloader.a(Preloader.java:72)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by shipengyan** [comment] 2017-12-16 13:18
me too

**Comment by mplushnikov** [comment] 2018-01-13 16:36
Please verify plugin version you are using. The last version (015.17.2) of plugin already contains a fix for it.
Close this as duplicate of #418

**Closed by mplushnikov** 2018-01-13 16:36 UTC
Labels: duplicate
