### ISSUE TITLE
Sometimes it works / sometimes doesn't

### ISSUE THREAD

**Issue by fedotxxl** [mplushnikov/lombok-intellij-plugin#117] opened 2015-06-21 13:37 UTC
Most of features (`@Slf4`j, `@AllArgsConstructor`, `val`, `@Getter`, `@Builder` etc) sometimes work / sometimes don't - IDEA can't resolve method. Manual resaving source file temporary fixes the problem.

This makes hard to use Lombok - it's easier to generate getters/constructors than have troubles with IDE.

**Comment by Janmm14** [comment] 2015-06-21 16:11
did you enabled annotation processing in the settings?

**Comment by fedotxxl** [comment] 2015-06-21 16:12
Yes, it's enabled - source code are correctly compiled

**Comment by mplushnikov** [comment] 2015-06-30 21:38
New plugin version 0.9.5 is available now, can you please verify your problem with new version?

**Comment by mplushnikov** [comment] 2015-07-14 22:25
I can't reproduce it after 0.9.5 any more. Will close this issue as done. Feel free to open new issue, if you find the problem again.

**Closed by mplushnikov** 2015-07-14 22:25 UTC
Labels: enhancement
