### ISSUE TITLE
@SneakyThrows on lambdas

### ISSUE THREAD

**Issue by depsypher** [mplushnikov/lombok-intellij-plugin#198] opened 2016-03-30 17:07 UTC
The following bug is reported against lombok itself, but I think it's a lombok-intellij-plugin bug:
https://github.com/rzwitserloot/lombok/issues/1038

Reposting the description here:
Intellij plugin incorrectly thinks that this @sneakythrows usage is valid:

@SneakyThrows(ClonableNotSupported.class)
void myfunc() {
...
List list = some-array-list...
list.forEach(o -> {
ClonableObj o1 = o.clone(); <-- this gives compile error (ClonableNotSupported? exception should be caught
});

However the annotation on the method incorrectly suppresses the IDE indication of that error. When you compile this code, it correctly points out that that "clone" line still throws unchecked exception AND that @sneakythrows is on a try block that doesn't throw exception. I suspect it's because lambda is an anonymous method of its own, so the clonable exception is thrown in that anonymous method and there's no way of attaching @SneakyThrows to it (or is there?)

So at a minimum, Intellij plugin should not suppress IDE compile error in this case.

**Comment by depsypher** [comment] 2016-03-30 17:25
After a bit more experimentation I find that the Problems view does correctly catch the error, but what's missing the the red underline of the code that throws the exception.

Additionally, if you've set up IntelliJ to use the Eclipse compiler, using SneakyThrows like this produces totally spurious errors.

**Comment by askoning** [comment] 2017-02-24 14:24
A similar (or even identical) issue was reported in rzwitserloot/lombok#1111.

**Comment by mplushnikov** [comment] 2021-02-02 19:28
Duplicate of #799, was fixed already by #951

**Closed by mplushnikov** 2021-02-02 19:28 UTC
