### ISSUE TITLE
Not Support Ultimate 2020.2

### ISSUE THREAD

**Issue by Qk1hpys** [mplushnikov/lombok-intellij-plugin#875] opened 2020-08-10 12:29 UTC
Too many exceptions to use my Idea... plz support 2020.2 as soon as possible

**Comment by valentinprotiuc** [comment] 2020-08-10 12:39
Duplicate of #840

**Comment by ruurd** [comment] 2020-08-11 09:52
Guys would you please do your due diligence on this in future? Don't spam the issue list before concluding someone else reported the bug before you.

**Closed** 2020-08-11 09:54 UTC

**Comment by ruurd** [comment] 2020-08-11 10:10
👍
