### ISSUE TITLE
com.intellij.diagnostic.PluginException

### ISSUE THREAD

**Issue by asarkar** [mplushnikov/lombok-intellij-plugin#823] opened 2020-06-23 17:52 UTC
### Short description
PluginException

### Expected behavior
No exceptions.

### Version information

 * **IDEA Version:** 2020.1.2, Build #IC-201.7846.76
 * **JDK Version:** 8.0.212
 * **OS Type & Version:** macOS 10.15.5
 * **Lombok Plugin Version:** 0.30-2020.1
 * **Lombok Dependency Version:** 1.18.4

### Steps to reproduce
_What steps do we need to take to reproduce this issue?_

 Don't know.

### Sample project
Please provide a sample project that exhibits the problem.
You should also include `.idea` folder so we can inspect the settings.

### Stacktrace

```

com.intellij.diagnostic.PluginException: class de.plushnikov.intellij.plugin.psi.LombokLightParameter; valid=true; method.valid=true [Plugin: Lombook Plugin]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:451)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:58)
	at com.intellij.codeInsight.daemon.impl.quickfix.ChangeMethodSignatureFromUsageFix.getNewParametersInfo(ChangeMethodSignatureFromUsageFix.java:327)
	at com.intellij.codeInsight.daemon.impl.quickfix.ChangeMethodSignatureFromUsageFix.isAvailable(ChangeMethodSignatureFromUsageFix.java:150)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.addAvailableFixesForGroups(ShowIntentionsPass.java:156)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:302)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:227)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:52)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:442)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:434)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:410)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:168)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:168)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:171)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl #JAVA  because: different providers: com.intellij.psi.DummyHolderViewProvider{vFile=LightVirtualFile: /DummyHolder, content=VirtualFileContent{size=0}, eventSystemEnabled=false}(7b221b03); com.intellij.psi.SingleRootFileViewProvider{vFile=LightVirtualFile: /DummyHolder, content=VirtualFileContent{size=0}, eventSystemEnabled=true}(6db11e1d)
invalidated at: see attachment; Type element reference of class com.intellij.psi.impl.source.PsiFieldImpl #PsiFieldImpl #Language: JAVA; augmenters=[com.intellij.psi.impl.source.JShellPsiAugmentProvider@1a257297, com.intellij.psi.impl.RecordAugmentProvider@30091ab, de.plushnikov.intellij.plugin.provider.LombokAugmentProvider@5b51d504]
	at com.intellij.psi.impl.source.PsiClassReferenceType.resolveGenerics(PsiClassReferenceType.java:174)
	at com.intellij.psi.impl.source.PsiClassReferenceType.resolve(PsiClassReferenceType.java:120)
	at com.intellij.psi.util.PsiUtil.ensureValidType(PsiUtil.java:1266)
	at com.intellij.psi.util.PsiUtil.ensureValidType(PsiUtil.java:1255)
	at com.intellij.codeInsight.daemon.impl.quickfix.ChangeMethodSignatureFromUsageFix.getNewParametersInfo(ChangeMethodSignatureFromUsageFix.java:321)
	... 22 more

```

**Comment by mplushnikov** [comment] 2020-08-12 18:25
Duplicate of #649

**Closed by mplushnikov** 2020-08-12 18:25 UTC
