### ISSUE TITLE
java.lang.AssertionError: Stub and PSI element type mismatch

### ISSUE THREAD

**Issue by ractive** [mplushnikov/lombok-intellij-plugin#100] opened 2015-04-16 12:55 UTC
I get those AssertionErrors quite a lot lately:

```
Stub and PSI element type mismatch in CategorySynonymManagementPresenter.java: stub PsiParameterStub[localUID:String], AST THROWS_LIST; Element(THROWS_LIST)
 file=PsiJavaFile:CategorySynonymManagementPresenter.java, modStamp=0
 stub debugInfo=created from index; with backReference
 document before=null
latestIndexedStub=com.intellij.psi.stubs.StubTree@6b58330f
   same size=false
   debugInfo=created from index; with backReference
 viewProvider=SingleRootFileViewProvider{myVirtualFile=file:///Users/james/devel/local.ch/backend/webapp_marvin/src/main/java/ch/local/marvinapplication/presenter/data/CategorySynonymManagementPresenter.java, content=DocumentContent{size=22746}}
 viewProvider stamp: 2958107; file stamp: 2958107; file modCount: 1429185421000
 doc saved: true; doc stamp: 2958107; doc size: 22746; committed: true
------------
: Stub and PSI element type mismatch in CategorySynonymManagementPresenter.java: stub PsiParameterStub[localUID:String], AST THROWS_LIST; Element(THROWS_LIST)
 file=PsiJavaFile:CategorySynonymManagementPresenter.java, modStamp=0
 stub debugInfo=created from index; with backReference
 document before=null
latestIndexedStub=com.intellij.psi.stubs.StubTree@6b58330f
   same size=false
   debugInfo=created from index; with backReference
 viewProvider=SingleRootFileViewProvider{myVirtualFile=file:///Users/james/devel/local.ch/backend/webapp_marvin/src/main/java/ch/local/marvinapplication/presenter/data/CategorySynonymManagementPresenter.java, content=DocumentContent{size=22746}}
 viewProvider stamp: 2958107; file stamp: 2958107; file modCount: 1429185421000
 doc saved: true; doc stamp: 2958107; doc size: 22746; committed: true
------------

java.lang.AssertionError: Stub and PSI element type mismatch in CategorySynonymManagementPresenter.java: stub PsiParameterStub[localUID:String], AST THROWS_LIST; Element(THROWS_LIST)
 file=PsiJavaFile:CategorySynonymManagementPresenter.java, modStamp=0
 stub debugInfo=created from index; with backReference
 document before=null
latestIndexedStub=com.intellij.psi.stubs.StubTree@6b58330f
   same size=false
   debugInfo=created from index; with backReference
 viewProvider=SingleRootFileViewProvider{myVirtualFile=file:///Users/james/devel/local.ch/backend/webapp_marvin/src/main/java/ch/local/marvinapplication/presenter/data/CategorySynonymManagementPresenter.java, content=DocumentContent{size=22746}}
 viewProvider stamp: 2958107; file stamp: 2958107; file modCount: 1429185421000
 doc saved: true; doc stamp: 2958107; doc size: 22746; committed: true
------------

	at com.intellij.psi.impl.source.PsiFileImpl.reportStubAstMismatch(PsiFileImpl.java:345)
	at com.intellij.psi.impl.source.PsiFileImpl$1.visitNode(PsiFileImpl.java:289)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor.visitComposite(RecursiveTreeElementWalkingVisitor.java:76)
	at com.intellij.psi.impl.source.tree.CompositeElement.acceptTree(CompositeElement.java:157)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor$1.visit(RecursiveTreeElementWalkingVisitor.java:65)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor$1.visit(RecursiveTreeElementWalkingVisitor.java:58)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:65)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor.visitNode(RecursiveTreeElementWalkingVisitor.java:81)
	at com.intellij.psi.impl.source.PsiFileImpl$1.visitNode(PsiFileImpl.java:298)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor.visitComposite(RecursiveTreeElementWalkingVisitor.java:76)
	at com.intellij.psi.impl.source.tree.CompositeElement.acceptTree(CompositeElement.java:157)
	at com.intellij.psi.impl.source.PsiFileImpl.a(PsiFileImpl.java:272)
	at com.intellij.psi.impl.source.PsiFileImpl.b(PsiFileImpl.java:204)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:777)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getNode(StubBasedPsiElementBase.java:87)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getText(ASTDelegatePsiElement.java:133)
	at de.plushnikov.intellij.plugin.util.PsiAnnotationUtil.extractAnnotationSimpleName(PsiAnnotationUtil.java:244)
	at de.plushnikov.intellij.plugin.util.PsiAnnotationUtil.checkAnnotationsSimpleNameExistsIn(PsiAnnotationUtil.java:261)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.verifyLombokAnnotationPresent(LombokAugmentProvider.java:154)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.checkLombokPresent(LombokAugmentProvider.java:108)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.getAugments(LombokAugmentProvider.java:95)
	at com.intellij.psi.augment.PsiAugmentProvider.collectAugments(PsiAugmentProvider.java:37)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.a(ClassInnerStuffCache.java:201)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.access$200(ClassInnerStuffCache.java:39)
	at com.intellij.psi.impl.source.ClassInnerStuffCache$2.compute(ClassInnerStuffCache.java:85)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:199)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.getFields(ClassInnerStuffCache.java:89)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.d(ClassInnerStuffCache.java:219)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.access$500(ClassInnerStuffCache.java:39)
	at com.intellij.psi.impl.source.ClassInnerStuffCache$5.compute(ClassInnerStuffCache.java:140)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:199)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.findFieldByName(ClassInnerStuffCache.java:144)
	at com.intellij.psi.impl.source.PsiClassImpl.findFieldByName(PsiClassImpl.java:376)
	at com.intellij.psi.impl.PsiClassImplUtil.a(PsiClassImplUtil.java:630)
	at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClass(PsiClassImplUtil.java:453)
	at com.intellij.psi.impl.source.PsiClassImpl.processDeclarations(PsiClassImpl.java:519)
	at com.intellij.psi.impl.source.PsiImportStaticReferenceElementImpl$OurGenericsResolver.resolve(PsiImportStaticReferenceElementImpl.java:238)
	at com.intellij.psi.impl.source.PsiImportStaticReferenceElementImpl$OurGenericsResolver.resolve(PsiImportStaticReferenceElementImpl.java:227)
	at com.intellij.psi.impl.source.resolve.ResolveCache$2.compute(ResolveCache.java:106)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:103)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:131)
	at com.intellij.psi.impl.source.PsiImportStaticReferenceElementImpl.multiResolve(PsiImportStaticReferenceElementImpl.java:223)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.a(PsiJavaFileBaseImpl.java:354)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processDeclarations(PsiJavaFileBaseImpl.java:290)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:72)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:54)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:215)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:146)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.a(PsiJavaCodeReferenceElementImpl.java:457)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$000(PsiJavaCodeReferenceElementImpl.java:55)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:339)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:330)
	at com.intellij.psi.impl.source.resolve.ResolveCache$2.compute(ResolveCache.java:106)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:103)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:131)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:385)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:359)
	at com.intellij.psi.impl.source.PsiClassReferenceType.resolveGenerics(PsiClassReferenceType.java:141)
	at com.intellij.psi.util.PsiUtil.captureToplevelWildcards(PsiUtil.java:681)
	at com.intellij.psi.impl.PsiClassImplUtil.getSuperTypes(PsiClassImplUtil.java:821)
	at com.intellij.psi.impl.source.PsiClassImpl.getSuperTypes(PsiClassImpl.java:262)
	at com.intellij.psi.impl.PsiClassImplUtil.a(PsiClassImplUtil.java:691)
	at com.intellij.psi.impl.PsiClassImplUtil.a(PsiClassImplUtil.java:677)
	at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClass(PsiClassImplUtil.java:453)
	at com.intellij.psi.impl.source.PsiClassImpl.processDeclarations(PsiClassImpl.java:519)
	at com.intellij.psi.impl.source.PsiImportStaticReferenceElementImpl$OurGenericsResolver.resolve(PsiImportStaticReferenceElementImpl.java:238)
	at com.intellij.psi.impl.source.PsiImportStaticReferenceElementImpl$OurGenericsResolver.resolve(PsiImportStaticReferenceElementImpl.java:227)
	at com.intellij.psi.impl.source.resolve.ResolveCache$2.compute(ResolveCache.java:106)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:103)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:131)
	at com.intellij.psi.impl.source.PsiImportStaticReferenceElementImpl.multiResolve(PsiImportStaticReferenceElementImpl.java:223)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.a(PsiJavaFileBaseImpl.java:354)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processDeclarations(PsiJavaFileBaseImpl.java:290)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:72)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:54)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:215)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:146)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.a(PsiJavaCodeReferenceElementImpl.java:457)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$000(PsiJavaCodeReferenceElementImpl.java:55)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:339)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:330)
	at com.intellij.psi.impl.source.resolve.ResolveCache$2.compute(ResolveCache.java:106)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:103)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:131)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:385)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:359)
	at com.intellij.psi.impl.source.PsiClassReferenceType.resolveGenerics(PsiClassReferenceType.java:141)
	at com.intellij.psi.util.PsiUtil.captureToplevelWildcards(PsiUtil.java:681)
	at com.intellij.psi.impl.PsiClassImplUtil.getSuperTypes(PsiClassImplUtil.java:821)
	at com.intellij.psi.impl.source.PsiClassImpl.getSuperTypes(PsiClassImpl.java:262)
	at com.intellij.psi.impl.PsiClassImplUtil.a(PsiClassImplUtil.java:691)
	at com.intellij.psi.impl.PsiClassImplUtil.a(PsiClassImplUtil.java:677)
	at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClass(PsiClassImplUtil.java:453)
	at com.intellij.psi.impl.source.PsiClassImpl.processDeclarations(PsiClassImpl.java:519)
	at com.intellij.psi.impl.source.PsiImportStaticReferenceElementImpl$OurGenericsResolver.resolve(PsiImportStaticReferenceElementImpl.java:238)
	at com.intellij.psi.impl.source.PsiImportStaticReferenceElementImpl$OurGenericsResolver.resolve(PsiImportStaticReferenceElementImpl.java:227)
	at com.intellij.psi.impl.source.resolve.ResolveCache$2.compute(ResolveCache.java:106)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:103)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:131)
	at com.intellij.psi.impl.source.PsiImportStaticReferenceElementImpl.multiResolve(PsiImportStaticReferenceElementImpl.java:223)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.a(PsiJavaFileBaseImpl.java:354)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processDeclarations(PsiJavaFileBaseImpl.java:290)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:72)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:54)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:215)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:146)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.a(PsiJavaCodeReferenceElementImpl.java:457)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$000(PsiJavaCodeReferenceElementImpl.java:55)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:339)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:330)
	at com.intellij.psi.impl.source.resolve.ResolveCache$2.compute(ResolveCache.java:106)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:103)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:131)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:385)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:359)
	at com.intellij.psi.impl.source.PsiClassReferenceType.resolveGenerics(PsiClassReferenceType.java:141)
	at com.intellij.psi.util.PsiUtil.captureToplevelWildcards(PsiUtil.java:681)
	at com.intellij.psi.impl.PsiClassImplUtil.getSuperTypes(PsiClassImplUtil.java:821)
	at com.intellij.psi.impl.source.PsiClassImpl.getSuperTypes(PsiClassImpl.java:262)
	at com.intellij.psi.impl.PsiClassImplUtil.a(PsiClassImplUtil.java:691)
	at com.intellij.psi.impl.PsiClassImplUtil.a(PsiClassImplUtil.java:677)
	at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClass(PsiClassImplUtil.java:453)
	at com.intellij.psi.impl.source.PsiClassImpl.processDeclarations(PsiClassImpl.java:519)
	at com.intellij.psi.impl.source.PsiImportStaticReferenceElementImpl$OurGenericsResolver.resolve(PsiImportStaticReferenceElementImpl.java:238)
	at com.intellij.psi.impl.source.PsiImportStaticReferenceElementImpl$OurGenericsResolver.resolve(PsiImportStaticReferenceElementImpl.java:227)
	at com.intellij.psi.impl.source.resolve.ResolveCache$2.compute(ResolveCache.java:106)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:103)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:131)
	at com.intellij.psi.impl.source.PsiImportStaticReferenceElementImpl.multiResolve(PsiImportStaticReferenceElementImpl.java:223)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.a(PsiJavaFileBaseImpl.java:354)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processDeclarations(PsiJavaFileBaseImpl.java:290)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:72)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:54)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:215)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:146)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.a(PsiJavaCodeReferenceElementImpl.java:457)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$000(PsiJavaCodeReferenceElementImpl.java:55)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:339)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:330)
	at com.intellij.psi.impl.source.resolve.ResolveCache$2.compute(ResolveCache.java:106)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:103)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:131)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:385)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:359)
	at com.intellij.psi.impl.source.PsiClassReferenceType.resolveGenerics(PsiClassReferenceType.java:141)
	at com.intellij.psi.impl.source.PsiClassReferenceType.resolve(PsiClassReferenceType.java:89)
	at com.intellij.psi.impl.PsiClassImplUtil.getSuperClass(PsiClassImplUtil.java:730)
	at com.intellij.psi.impl.source.PsiClassImpl.getSuperClass(PsiClassImpl.java:245)
	at com.intellij.psi.impl.InheritanceImplUtil.b(InheritanceImplUtil.java:164)
	at com.intellij.psi.impl.InheritanceImplUtil.a(InheritanceImplUtil.java:128)
	at com.intellij.psi.impl.InheritanceImplUtil.isInheritor(InheritanceImplUtil.java:58)
	at com.intellij.psi.impl.source.PsiClassImpl.isInheritor(PsiClassImpl.java:650)
	at com.intellij.psi.util.InheritanceUtil.isInheritorOrSelf(InheritanceUtil.java:41)
	at com.intellij.psi.util.TypeConversionUtil.isClassAssignable(TypeConversionUtil.java:905)
	at com.intellij.psi.util.TypeConversionUtil.isAssignable(TypeConversionUtil.java:817)
	at com.intellij.psi.util.TypeConversionUtil.typesAgree(TypeConversionUtil.java:991)
	at com.intellij.psi.util.TypeConversionUtil.typeParametersAgree(TypeConversionUtil.java:941)
	at com.intellij.psi.util.TypeConversionUtil.isClassAssignable(TypeConversionUtil.java:905)
	at com.intellij.psi.util.TypeConversionUtil.isAssignable(TypeConversionUtil.java:817)
	at com.intellij.psi.util.PsiUtil.getApplicabilityLevel(PsiUtil.java:494)
	at com.intellij.psi.util.PsiUtil.getApplicabilityLevel(PsiUtil.java:473)
	at com.intellij.psi.infos.MethodCandidateInfo.getApplicabilityLevelInner(MethodCandidateInfo.java:92)
	at com.intellij.psi.infos.MethodCandidateInfo.getApplicabilityLevel(MethodCandidateInfo.java:101)
	at com.intellij.psi.infos.MethodCandidateInfo.isApplicable(MethodCandidateInfo.java:83)
	at com.intellij.psi.infos.MethodCandidateInfo.isValidResult(MethodCandidateInfo.java:234)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightMethodUtil.checkMethodCall(HighlightMethodUtil.java:341)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visitMethodCallExpression(HighlightVisitorImpl.java:838)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.accept(PsiMethodCallExpressionImpl.java:135)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visit(HighlightVisitorImpl.java:136)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$5.run(GeneralHighlightingPass.java:312)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:397)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$300(GeneralHighlightingPass.java:64)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$6.run(GeneralHighlightingPass.java:403)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:87)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:400)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$300(GeneralHighlightingPass.java:64)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$6.run(GeneralHighlightingPass.java:403)
	at com.intellij.codeInsight.daemon.impl.RefCountHolder.analyze(RefCountHolder.java:318)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:173)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:400)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:388)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:230)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:86)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:62)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:380)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:371)
	at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:368)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:344)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:193)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
```

**Comment by mplushnikov** [comment] 2015-04-26 09:39
What are your IntelliJ and JDK versions? OS?

**Comment by mplushnikov** [comment] 2015-04-28 20:57
Looks like duplicate of #72

**Closed** 2015-04-29 19:11 UTC
Labels: bug
