### ISSUE TITLE
@AllArgsConstructor with generic type not compiling with 13.1.5 intellij

### ISSUE THREAD

**Issue by dcapwell** [mplushnikov/lombok-intellij-plugin#69] opened 2014-11-08 19:18 UTC
Lombok version: org.projectlombok:lombok:1.14.8
Intellij Plugin: 0.8.8
Intellij: 13.1.5
Java: 8

The following doesn't compile

```java
@AllArgsConstructor
private static final class Entity<K, V> {
  private final K key;
  V value;
}
```

```java
new Entity<>(key, value)

Error:(58, 15) java: cannot infer type arguments for com.github.dcapwell.collect.mutable.HashMap.Entity<>
  reason: cannot infer type-variable(s) K,V
    (actual and formal argument lists differ in length)
```

When I build from gradle, works just fine.

**Comment by Janmm14** [comment] 2015-01-03 13:46
Unfortunally I can't reproduce it right now too as the class i needed this combination is now removed and replaced.

**Comment by mplushnikov** [comment] 2015-01-05 08:23
Ok, I will close this as invalid. Feel free to reopen if you find another example.

**Closed by mplushnikov** 2015-01-05 08:23 UTC
Labels: invalid
