### ISSUE TITLE
Add Support for @With

### ISSUE THREAD

**Issue by michaelamaura** [mplushnikov/lombok-intellij-plugin#675] opened 2019-09-30 16:04 UTC
### Short description

With lombok 1.18.10 `@Wither` has been promoted to stable as `@With`.

Currently this does not seem to work. At least IntelliJ IDEA will generate warnings like the following:

```
Class xyz does not implement method ...
```

### Expected behavior

`@With` should behabe just the same as `@Wither`

### Version information

0.26.2

**Comment by mplushnikov** [comment] 2019-09-30 17:02
Duplicate of #673. New plugin version will be probably released this week.

**Closed by mplushnikov** 2019-09-30 17:02 UTC
Labels: duplicate
