### ISSUE TITLE
StackOverflowError when executing 'Guava's primitives can be replaced by Java API' action

### ISSUE THREAD

**Issue by stsypanov** [mplushnikov/lombok-intellij-plugin#288] opened 2016-09-02 14:11 UTC
In IDEA2016.2.3 (#IU-162-1812-17, August 30) run mentioned replacement action on the following code:

``` java
public Set<String> getRegionCodeList(Set<RegionType> regions) {
        return FluentIterable.from(regions).transform(GetCode.FUNC).toSet();
    }
```

where

``` java
public enum GetCode implements com.google.common.base.Function<HasCode, String>, java.util.function.Function<HasCode, String> {
    FUNC;

    @Override
    public String apply(HasCode e) {
        return e.getCode();
    }
}

//and

public interface HasCode {
    String getCode();
}
```

You get the following exception:

Exception message: null
<pre>
java.lang.StackOverflowError
        at com.intellij.psi.impl.source.tree.CompositeElement.countChildren(CompositeElement.java:514)
        at com.intellij.psi.impl.source.tree.CompositeElement.getChildren(CompositeElement.java:459)
        at com.intellij.lang.TreeBackedLighterAST.getChildren(TreeBackedLighterAST.java:47)
        at com.intellij.psi.impl.source.tree.LightTreeUtil.toBuffer(LightTreeUtil.java:146)
        at com.intellij.psi.impl.source.tree.LightTreeUtil.toBuffer(LightTreeUtil.java:148)
        at com.intellij.psi.impl.source.tree.LightTreeUtil.toBuffer(LightTreeUtil.java:148)
        at com.intellij.psi.impl.source.tree.LightTreeUtil.toBuffer(LightTreeUtil.java:148)
        at com.intellij.psi.impl.source.tree.LightTreeUtil.toBuffer(LightTreeUtil.java:148)
        at com.intellij.psi.impl.source.tree.LightTreeUtil.toBuffer(LightTreeUtil.java:148)
        at com.intellij.psi.impl.source.tree.LightTreeUtil.toBuffer(LightTreeUtil.java:148)
        at com.intellij.psi.impl.source.tree.LightTreeUtil.toFilteredString(LightTreeUtil.java:127)
        at com.intellij.psi.impl.source.tree.JavaSourceUtil.getReferenceText(JavaSourceUtil.java:114)
        at com.intellij.psi.impl.java.stubs.JavaImportStatementElementType.createStub(JavaImportStatementElementType.java:71)
        at com.intellij.psi.impl.java.stubs.JavaImportStatementElementType.createStub(JavaImportStatementElementType.java:43)
        at com.intellij.psi.stubs.LightStubBuilder.createStub(LightStubBuilder.java:140)
        at com.intellij.psi.stubs.LightStubBuilder.buildStubTree(LightStubBuilder.java:92)
        at com.intellij.psi.stubs.LightStubBuilder.buildStubTree(LightStubBuilder.java:68)
        at com.intellij.psi.stubs.StubTreeBuilder.buildStubTree(StubTreeBuilder.java:86)
        at com.intellij.psi.stubs.StubUpdatingIndex$4.a(StubUpdatingIndex.java:209)
        at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:851)
        at com.intellij.psi.stubs.StubUpdatingIndex$4.map(StubUpdatingIndex.java:208)
        at com.intellij.psi.stubs.StubUpdatingIndex$4.map(StubUpdatingIndex.java:191)
        at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:457)
        at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1322)
        at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:505)
        at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1297)
        at com.intellij.util.indexing.FileBasedIndexImpl.access$4200(FileBasedIndexImpl.java:103)
        at com.intellij.util.indexing.FileBasedIndexImpl$DocumentUpdateTask.doProcess(FileBasedIndexImpl.java:2310)
        at com.intellij.util.indexing.FileBasedIndexImpl$DocumentUpdateTask.doProcess(FileBasedIndexImpl.java:2301)
        at com.intellij.util.indexing.UpdateTask.a(UpdateTask.java:80)
        at com.intellij.util.indexing.UpdateTask.processAll(UpdateTask.java:47)
        at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1205)
        at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:714)
        at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:681)
        at com.intellij.psi.stubs.StubIndexImpl.a(StubIndexImpl.java:335)
        at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:316)
        at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:146)
        at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:135)
        at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.get(JavaFullClassNameIndex.java:48)
        at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.a(JavaFileManagerImpl.java:91)
        at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClass(JavaFileManagerImpl.java:126)
        at com.intellij.psi.impl.PsiElementFinderImpl.findClass(PsiElementFinderImpl.java:54)
        at com.intellij.psi.impl.JavaPsiFacadeImpl.b(JavaPsiFacadeImpl.java:122)
        at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:99)
        at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.a(PsiJavaCodeReferenceElementImpl.java:395)
        at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:55)
        at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:350)
        at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:342)
        at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:191)
        at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:188)
        at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
        at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:188)
        at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:745)
        at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:734)
        at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:377)
        at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:370)
        at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:339)
        at com.intellij.psi.impl.source.PsiImportStatementBaseImpl.resolve(PsiImportStatementBaseImpl.java:64)
        at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.a(PsiJavaFileBaseImpl.java:329)
        at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.access$200(PsiJavaFileBaseImpl.java:58)
        at com.intellij.psi.impl.source.PsiJavaFileBaseImpl$MyCacheBuilder.compute(PsiJavaFileBaseImpl.java:511)
        at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
        at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
        at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:65)
        at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
        at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processDeclarations(PsiJavaFileBaseImpl.java:298)
        at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:68)
        at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:50)
        at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:226)
        at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:157)
        at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.a(PsiJavaCodeReferenceElementImpl.java:448)
        at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:55)
        at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:350)
        at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:342)
        at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:191)
        at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:188)
        at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
        at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:188)
        at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:745)
        at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.a(PsiJavaCodeReferenceElementImpl.java:277)
        at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.getCanonicalText(PsiJavaCodeReferenceElementImpl.java:262)
        at com.intellij.psi.impl.source.tree.java.PsiAnnotationImpl.getQualifiedName(PsiAnnotationImpl.java:96)
        at com.intellij.codeInsight.AnnotationUtil$1$1.create(AnnotationUtil.java:133)
        at com.intellij.codeInsight.AnnotationUtil$1$1.create(AnnotationUtil.java:126)
        at com.intellij.util.containers.FactoryMap.get(FactoryMap.java:56)
        at com.intellij.codeInsight.AnnotationUtil.findOwnAnnotation(AnnotationUtil.java:143)
        at com.intellij.codeInsight.AnnotationUtil.findAnnotation(AnnotationUtil.java:112)
        at com.intellij.codeInsight.AnnotationUtil.findAnnotation(AnnotationUtil.java:95)
        at de.plushnikov.intellij.plugin.util.PsiAnnotationUtil.findAnnotation(PsiAnnotationUtil.java:54)
        at de.plushnikov.intellij.plugin.processor.method.AbstractMethodProcessor.process(AbstractMethodProcessor.java:39)
        at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.process(LombokAugmentProvider.java:150)
        at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.getAugments(LombokAugmentProvider.java:102)
        at com.intellij.psi.augment.PsiAugmentProvider$1.process(PsiAugmentProvider.java:95)
        at com.intellij.psi.augment.PsiAugmentProvider$1.process(PsiAugmentProvider.java:92)
        at com.intellij.psi.augment.PsiAugmentProvider.forEach(PsiAugmentProvider.java:146)
        at com.intellij.psi.augment.PsiAugmentProvider.collectAugments(PsiAugmentProvider.java:92)
        at com.intellij.psi.impl.source.ClassInnerStuffCache.e(ClassInnerStuffCache.java:177)
        at com.intellij.psi.impl.source.ClassInnerStuffCache.access$400(ClassInnerStuffCache.java:38)
        at com.intellij.psi.impl.source.ClassInnerStuffCache$4.compute(ClassInnerStuffCache.java:86)
        at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:137)
        at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
        at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
        at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:65)
        at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
        at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:130)
        at com.intellij.psi.impl.source.ClassInnerStuffCache.getInnerClasses(ClassInnerStuffCache.java:82)
        at com.intellij.psi.impl.source.ClassInnerStuffCache.a(ClassInnerStuffCache.java:220)
        at com.intellij.psi.impl.source.ClassInnerStuffCache.access$700(ClassInnerStuffCache.java:38)
        at com.intellij.psi.impl.source.ClassInnerStuffCache$7.compute(ClassInnerStuffCache.java:130)
        at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:137)
        at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
        at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
        at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:65)
        at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
        at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:130)
        at com.intellij.psi.impl.source.ClassInnerStuffCache.findInnerClassByName(ClassInnerStuffCache.java:126)
        at com.intellij.psi.impl.source.PsiClassImpl.findInnerClassByName(PsiClassImpl.java:400)
        at com.intellij.psi.impl.PsiClassImplUtil.a(PsiClassImplUtil.java:552)
        at com.intellij.psi.impl.PsiClassImplUtil.a(PsiClassImplUtil.java:481)
        at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClass(PsiClassImplUtil.java:458)
        at com.intellij.psi.impl.source.PsiClassImpl.processDeclarations(PsiClassImpl.java:491)
        at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:68)
        at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:50)
        at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:226)
        at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:157)
        at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.a(PsiReferenceExpressionImpl.java:331)
        at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.a(PsiReferenceExpressionImpl.java:269)
        at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.access$000(PsiReferenceExpressionImpl.java:61)
        at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolve(PsiReferenceExpressionImpl.java:196)
        at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolve(PsiReferenceExpressionImpl.java:185)
        at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:191)
        at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:188)
        at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
        at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:188)
        at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:745)
        at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:734)
        at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.multiResolve(PsiReferenceExpressionImpl.java:345)
        at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionBase.advancedResolve(PsiReferenceExpressionBase.java:86)
        at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionBase.resolve(PsiReferenceExpressionBase.java:48)
        at com.intellij.psi.impl.source.tree.JavaTreeCopyHandler.decodeInformation(JavaTreeCopyHandler.java:53)
        at com.intellij.psi.impl.source.tree.ChangeUtil.a(ChangeUtil.java:94)
        at com.intellij.psi.impl.source.tree.ChangeUtil.a(ChangeUtil.java:89)
        at com.intellij.psi.impl.source.tree.ChangeUtil.decodeInformation(ChangeUtil.java:79)
        at com.intellij.psi.impl.source.tree.SharedImplUtil.doReplace(SharedImplUtil.java:212)
        at com.intellij.psi.impl.source.tree.CompositePsiElement.replace(CompositePsiElement.java:212)
        at com.intellij.refactoring.typeMigration.rules.guava.GuavaConversionUtil.adjustLambdaContainingExpression(GuavaConversionUtil.java:127)
        at com.intellij.refactoring.typeMigration.rules.guava.GuavaConversionUtil.adjustLambdaContainingExpression(GuavaConversionUtil.java:139)
        at com.intellij.refactoring.typeMigration.rules.guava.GuavaConversionUtil.adjustLambdaContainingExpression(GuavaConversionUtil.java:127)
        at com.intellij.refactoring.typeMigration.rules.guava.GuavaConversionUtil.adjustLambdaContainingExpression(GuavaConversionUtil.java:139)
        at .......
</pre>

**Comment by mplushnikov** [comment] 2018-01-13 21:29
Still reproducable with stacktrace:
```
java.lang.Exception
	at com.intellij.psi.stubs.StubTreeLoaderImpl.diagnoseLengthMismatch(StubTreeLoaderImpl.java:175)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.checkLengthMatch(StubTreeLoaderImpl.java:145)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:113)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readOrBuild(StubTreeLoaderImpl.java:53)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:651)
	at com.intellij.psi.impl.source.PsiFileImpl.getGreenStubTree(PsiFileImpl.java:1021)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubbedSpine(PsiFileImpl.java:235)
	at com.intellij.psi.PsiAnchor.restoreFromStubIndex(PsiAnchor.java:402)
	at com.intellij.psi.impl.smartPointers.AnchorElementInfo.restoreElement(AnchorElementInfo.java:72)
	at com.intellij.psi.impl.smartPointers.SmartPsiElementPointerImpl.doRestoreElement(SmartPsiElementPointerImpl.java:89)
	at com.intellij.psi.impl.smartPointers.SmartPsiElementPointerImpl.getElement(SmartPsiElementPointerImpl.java:80)
	at com.intellij.ide.projectView.impl.nodes.PsiTreeAnchorizer.lambda$retrieveElement$1(PsiTreeAnchorizer.java:47)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.ide.projectView.impl.nodes.PsiTreeAnchorizer.retrieveElement(PsiTreeAnchorizer.java:47)
	at com.intellij.ide.util.treeView.AbstractTreeNode.getValue(AbstractTreeNode.java:149)
	at com.intellij.ide.projectView.impl.ProjectViewTree.lambda$getFileColorFor$0(ProjectViewTree.java:120)
	at com.intellij.ide.projectView.impl.ProjectViewTree.getColorForObject(ProjectViewTree.java:132)
	at com.intellij.ide.projectView.impl.ProjectViewTree.getFileColorFor(ProjectViewTree.java:118)
	at com.intellij.ui.treeStructure.Tree.getFileColorForPath(Tree.java:377)
	at com.intellij.ui.treeStructure.Tree.paintFileColorGutter(Tree.java:358)
	at com.intellij.ui.treeStructure.Tree.paintComponent(Tree.java:343)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at com.intellij.ui.treeStructure.Tree.paint(Tree.java:260)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JViewport.paint(JViewport.java:728)
	at com.intellij.ui.components.JBViewport.paint(JBViewport.java:236)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at com.intellij.openapi.wm.impl.ToolWindowsPane.paintChildren(ToolWindowsPane.java:183)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5217)
	at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:290)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent.paint(JComponent.java:1042)
	at java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:79)
	at sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:116)
	at java.awt.Container.paint(Container.java:1975)
	at java.awt.Window.paint(Window.java:3904)
	at com.intellij.openapi.wm.impl.IdeFrameImpl.paint(IdeFrameImpl.java:455)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:842)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
Reported to Jetbrains:
https://ea.jetbrains.com/browser/ea_reports/1705916

**Comment by mplushnikov** [comment] 2020-09-05 19:02
Looks like be already fixed in the current IntelliJ version.

**Closed by mplushnikov** 2020-09-05 19:02 UTC
Labels: needIntellijDeveloperSupport
