### ISSUE TITLE
Lombok Plugin broken with Dec 4 release 2018.3

### ISSUE THREAD

**Issue by mikeppp** [mplushnikov/lombok-intellij-plugin#561] opened 2018-12-05 21:53 UTC
### Short description
Plugin is not compatible with Dec 4 release of 2018.3

### Expected behavior
It should load.

### Version information

 * **IDEA Version:** 2018.3 
 * **JDK Version:** JDK 1.8.181
 * **OS Type & Version:** MacOsX Mojave
 * **Lombok Plugin Version:** V0.22.IDEA-EAP
 * **Lombok Dependency Version:** 1.18.2

### Steps to reproduce
_What steps do we need to take to reproduce this issue?_

 1. Upgrade to Dec 4 release of IntelliJ 2018.3 (ultimate)
 2. You get error that plugin is not compatible

### Sample project
Please provide a sample project that exhibits the problem.
You should also include `.idea` folder so we can inspect the settings.

 - [ ] Sample project provided
 - [ ] I am able to reproduce this error on the sample project by following the steps described above

### Additional information
_Is there any additional information you can provide to help us understanding and solving the issue?_

### Stacktrace
If you are experiencing an issue and IntelliJ throws an error please provide the stacktrace.

```

STACKTRACE HERE (inside code markup)

```

**Comment by leewc** [comment] 2018-12-06 19:30
Looks like this is already being tracked in https://github.com/mplushnikov/lombok-intellij-plugin/issues/556 :)

**Comment by mplushnikov** [comment] 2018-12-10 13:49
I's duplicate of #556

**Closed by mplushnikov** 2018-12-10 13:49 UTC
