### ISSUE TITLE
Using final fields with @AllArgsConstructor annotation still causes warnings

### ISSUE THREAD

**Issue by raoulvdberge** [mplushnikov/lombok-intellij-plugin#887] opened 2020-08-16 15:11 UTC
### Short description
When having a class that uses `@AllArgsConstructor` in combination with final fields, I still get warnings in IntelliJ about the final fields not being initialized.

![image](https://user-images.githubusercontent.com/10358424/90337489-1f110200-dfe3-11ea-86c3-88737a55a544.png)

### Expected behavior
I expect IntelliJ to know that the constructor to initialize the final fields is available through the `@AllArgsConstructor` annotation.

### Version information

 * **IDEA Version:**
```
IntelliJ IDEA 2020.2 (Ultimate Edition)
Build #IU-202.6397.94, built on July 27, 2020
Runtime version: 11.0.7+10-b944.20 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1998M
Cores: 4
Registry: compiler.automake.allow.when.app.running=true
Non-Bundled Plugins: Lombook Plugin, com.intellij.kubernetes, org.toml.lang, intellij.prettierJS
```
 * **JDK Version:** JDK 11.0.4
 * **OS Type & Version:** Windows 10
 * **Lombok Plugin Version:** 0.30-EAP
 * **Lombok Dependency Version:** lombok-1.18.12.jar

### Steps to reproduce
 1. Create a class
 2. Add final fields
 3. Add the `@AllArgsConstructor`

(Step 2 and 3 can be switched.)

### Additional information
Closing and re-opening the IntelliJ project fixes the issue.

**Comment by meiblorn** [comment] 2020-08-17 00:49
Related to https://github.com/mplushnikov/lombok-intellij-plugin/issues/829

**Comment by mplushnikov** [comment] 2020-08-17 07:19
lombok plugin is currently not functional for IntelliJ 2020.2, close as duplicate of #829 and #840

**Closed by mplushnikov** 2020-08-17 07:19 UTC
